// Copyright (c) 2015, Cisco Systems
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//
// 1. Redistributions of source code must retain the above copyright notice,
//    this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
// TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
// LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// This file is autogenerated
//
// The following edits are possible, without affecting the validity of the
// file:
//
//  * Fields may be renamed.
//  * Fields may be deleted.
//  * The unique numbered tag for a field may be changed, provided that
//    the ordering of tags for fields within a message is preserved.
//  * Message types may be renamed.
//  * Message types may be deleted (if all fields that reference them
//    have been deleted).
//
// All Cisco message and field extensions must be preserved (except when the
// field itself is being deleted).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: cisco_ios_xr_ipv6_acl_oper/ipv6_acl_and_prefix_list/access_list_manager/prefixes/prefix/prefix_list_sequences/prefix_list_sequence/ipv6_pfx_edm_ace.proto

package cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Prefix list entry BAG
type Ipv6PfxEdmAce_KEYS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrefixListName string `protobuf:"bytes,1,opt,name=prefix_list_name,json=prefixListName,proto3" json:"prefix_list_name,omitempty"`
	SequenceNumber uint32 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
}

func (x *Ipv6PfxEdmAce_KEYS) Reset() {
	*x = Ipv6PfxEdmAce_KEYS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ipv6PfxEdmAce_KEYS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ipv6PfxEdmAce_KEYS) ProtoMessage() {}

func (x *Ipv6PfxEdmAce_KEYS) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ipv6PfxEdmAce_KEYS.ProtoReflect.Descriptor instead.
func (*Ipv6PfxEdmAce_KEYS) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto_rawDescGZIP(), []int{0}
}

func (x *Ipv6PfxEdmAce_KEYS) GetPrefixListName() string {
	if x != nil {
		return x.PrefixListName
	}
	return ""
}

func (x *Ipv6PfxEdmAce_KEYS) GetSequenceNumber() uint32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

type Ipv6PfxEdmAce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ACE type (acl, remark)
	IsAceType string `protobuf:"bytes,50,opt,name=is_ace_type,json=isAceType,proto3" json:"is_ace_type,omitempty"`
	// ACLE sequence number
	IsAceSequenceNumber uint32 `protobuf:"varint,51,opt,name=is_ace_sequence_number,json=isAceSequenceNumber,proto3" json:"is_ace_sequence_number,omitempty"`
	// Grant value permit/deny
	IsPacketAllowOrDeny string `protobuf:"bytes,52,opt,name=is_packet_allow_or_deny,json=isPacketAllowOrDeny,proto3" json:"is_packet_allow_or_deny,omitempty"`
	// IPv6 prefix
	IsAddressInNumbers string `protobuf:"bytes,53,opt,name=is_address_in_numbers,json=isAddressInNumbers,proto3" json:"is_address_in_numbers,omitempty"`
	// Prefix length
	IsAddressMaskLength uint32 `protobuf:"varint,54,opt,name=is_address_mask_length,json=isAddressMaskLength,proto3" json:"is_address_mask_length,omitempty"`
	// Port Operator
	IsLengthOperator string `protobuf:"bytes,55,opt,name=is_length_operator,json=isLengthOperator,proto3" json:"is_length_operator,omitempty"`
	// Min length
	IsPacketMinimumLength uint32 `protobuf:"varint,56,opt,name=is_packet_minimum_length,json=isPacketMinimumLength,proto3" json:"is_packet_minimum_length,omitempty"`
	// Maximum length
	IsPacketMaximumLength uint32 `protobuf:"varint,57,opt,name=is_packet_maximum_length,json=isPacketMaximumLength,proto3" json:"is_packet_maximum_length,omitempty"`
	// Number of hits
	Hits uint32 `protobuf:"varint,58,opt,name=hits,proto3" json:"hits,omitempty"`
	// Remark String
	IsCommentForEntry string `protobuf:"bytes,59,opt,name=is_comment_for_entry,json=isCommentForEntry,proto3" json:"is_comment_for_entry,omitempty"`
	// ACL Name
	AclName string `protobuf:"bytes,60,opt,name=acl_name,json=aclName,proto3" json:"acl_name,omitempty"`
}

func (x *Ipv6PfxEdmAce) Reset() {
	*x = Ipv6PfxEdmAce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ipv6PfxEdmAce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ipv6PfxEdmAce) ProtoMessage() {}

func (x *Ipv6PfxEdmAce) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ipv6PfxEdmAce.ProtoReflect.Descriptor instead.
func (*Ipv6PfxEdmAce) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto_rawDescGZIP(), []int{1}
}

func (x *Ipv6PfxEdmAce) GetIsAceType() string {
	if x != nil {
		return x.IsAceType
	}
	return ""
}

func (x *Ipv6PfxEdmAce) GetIsAceSequenceNumber() uint32 {
	if x != nil {
		return x.IsAceSequenceNumber
	}
	return 0
}

func (x *Ipv6PfxEdmAce) GetIsPacketAllowOrDeny() string {
	if x != nil {
		return x.IsPacketAllowOrDeny
	}
	return ""
}

func (x *Ipv6PfxEdmAce) GetIsAddressInNumbers() string {
	if x != nil {
		return x.IsAddressInNumbers
	}
	return ""
}

func (x *Ipv6PfxEdmAce) GetIsAddressMaskLength() uint32 {
	if x != nil {
		return x.IsAddressMaskLength
	}
	return 0
}

func (x *Ipv6PfxEdmAce) GetIsLengthOperator() string {
	if x != nil {
		return x.IsLengthOperator
	}
	return ""
}

func (x *Ipv6PfxEdmAce) GetIsPacketMinimumLength() uint32 {
	if x != nil {
		return x.IsPacketMinimumLength
	}
	return 0
}

func (x *Ipv6PfxEdmAce) GetIsPacketMaximumLength() uint32 {
	if x != nil {
		return x.IsPacketMaximumLength
	}
	return 0
}

func (x *Ipv6PfxEdmAce) GetHits() uint32 {
	if x != nil {
		return x.Hits
	}
	return 0
}

func (x *Ipv6PfxEdmAce) GetIsCommentForEntry() string {
	if x != nil {
		return x.IsCommentForEntry
	}
	return ""
}

func (x *Ipv6PfxEdmAce) GetAclName() string {
	if x != nil {
		return x.AclName
	}
	return ""
}

var File_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto protoreflect.FileDescriptor

var file_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto_rawDesc = []byte{
	0x0a, 0x99, 0x01, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f, 0x78, 0x72, 0x5f,
	0x69, 0x70, 0x76, 0x36, 0x5f, 0x61, 0x63, 0x6c, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x2f, 0x69, 0x70,
	0x76, 0x36, 0x5f, 0x61, 0x63, 0x6c, 0x5f, 0x61, 0x6e, 0x64, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69,
	0x78, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x2f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x65, 0x66, 0x69,
	0x78, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x2f, 0x70, 0x72, 0x65, 0x66, 0x69,
	0x78, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x73,
	0x2f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x69, 0x70, 0x76, 0x36, 0x5f, 0x70, 0x66, 0x78, 0x5f, 0x65,
	0x64, 0x6d, 0x5f, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x82, 0x01, 0x63,
	0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f, 0x78, 0x72, 0x5f, 0x69, 0x70, 0x76, 0x36,
	0x5f, 0x61, 0x63, 0x6c, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x2e, 0x69, 0x70, 0x76, 0x36, 0x5f, 0x61,
	0x63, 0x6c, 0x5f, 0x61, 0x6e, 0x64, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x2e, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x2e, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x5f, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x65,
	0x66, 0x69, 0x78, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x65, 0x22, 0x6a, 0x0a, 0x15, 0x69, 0x70, 0x76, 0x36, 0x5f, 0x70, 0x66, 0x78, 0x5f, 0x65, 0x64,
	0x6d, 0x5f, 0x61, 0x63, 0x65, 0x5f, 0x4b, 0x45, 0x59, 0x53, 0x12, 0x28, 0x0a, 0x10, 0x70, 0x72,
	0x65, 0x66, 0x69, 0x78, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x4c, 0x69, 0x73, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x73,
	0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x85, 0x04,
	0x0a, 0x10, 0x69, 0x70, 0x76, 0x36, 0x5f, 0x70, 0x66, 0x78, 0x5f, 0x65, 0x64, 0x6d, 0x5f, 0x61,
	0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x32, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x73, 0x41, 0x63, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x33, 0x0a, 0x16, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x71,
	0x75, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x33, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x13, 0x69, 0x73, 0x41, 0x63, 0x65, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x17, 0x69, 0x73, 0x5f, 0x70, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x5f, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x6f, 0x72, 0x5f, 0x64, 0x65,
	0x6e, 0x79, 0x18, 0x34, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x69, 0x73, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x4f, 0x72, 0x44, 0x65, 0x6e, 0x79, 0x12, 0x31, 0x0a,
	0x15, 0x69, 0x73, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x69, 0x6e, 0x5f, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x35, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x69, 0x73,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x12, 0x33, 0x0a, 0x16, 0x69, 0x73, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x6d,
	0x61, 0x73, 0x6b, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x36, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x13, 0x69, 0x73, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x4d, 0x61, 0x73, 0x6b, 0x4c,
	0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x2c, 0x0a, 0x12, 0x69, 0x73, 0x5f, 0x6c, 0x65, 0x6e, 0x67,
	0x74, 0x68, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x37, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x69, 0x73, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x12, 0x37, 0x0a, 0x18, 0x69, 0x73, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x5f, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18,
	0x38, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x15, 0x69, 0x73, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x4d,
	0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x37, 0x0a, 0x18,
	0x69, 0x73, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75,
	0x6d, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x39, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x15,
	0x69, 0x73, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x4c,
	0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x74, 0x73, 0x18, 0x3a, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x68, 0x69, 0x74, 0x73, 0x12, 0x2f, 0x0a, 0x14, 0x69, 0x73, 0x5f,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x65, 0x6e, 0x74, 0x72,
	0x79, 0x18, 0x3b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x69, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x46, 0x6f, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x63,
	0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x3c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63,
	0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto_rawDescOnce sync.Once
	file_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto_rawDescData = file_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto_rawDesc
)

func file_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto_rawDescGZIP() []byte {
	file_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto_rawDescOnce.Do(func() {
		file_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto_rawDescData = protoimpl.X.CompressGZIP(file_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto_rawDescData)
	})
	return file_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto_rawDescData
}

var file_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto_goTypes = []interface{}{
	(*Ipv6PfxEdmAce_KEYS)(nil), // 0: cisco_ios_xr_ipv6_acl_oper.ipv6_acl_and_prefix_list.access_list_manager.prefixes.prefix.prefix_list_sequences.prefix_list_sequence.ipv6_pfx_edm_ace_KEYS
	(*Ipv6PfxEdmAce)(nil),      // 1: cisco_ios_xr_ipv6_acl_oper.ipv6_acl_and_prefix_list.access_list_manager.prefixes.prefix.prefix_list_sequences.prefix_list_sequence.ipv6_pfx_edm_ace
}
var file_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() {
	file_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto_init()
}
func file_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto_init() {
	if File_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ipv6PfxEdmAce_KEYS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ipv6PfxEdmAce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto_goTypes,
		DependencyIndexes: file_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto_depIdxs,
		MessageInfos:      file_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto_msgTypes,
	}.Build()
	File_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto = out.File
	file_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto_rawDesc = nil
	file_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto_goTypes = nil
	file_cisco_ios_xr_ipv6_acl_oper_ipv6_acl_and_prefix_list_access_list_manager_prefixes_prefix_prefix_list_sequences_prefix_list_sequence_ipv6_pfx_edm_ace_proto_depIdxs = nil
}
