// Copyright (c) 2015, Cisco Systems
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//
// 1. Redistributions of source code must retain the above copyright notice,
//    this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
// TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
// LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// This file is autogenerated
//
// The following edits are possible, without affecting the validity of the
// file:
//
//  * Fields may be renamed.
//  * Fields may be deleted.
//  * The unique numbered tag for a field may be changed, provided that
//    the ordering of tags for fields within a message is preserved.
//  * Message types may be renamed.
//  * Message types may be deleted (if all fields that reference them
//    have been deleted).
//
// All Cisco message and field extensions must be preserved (except when the
// field itself is being deleted).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: cisco_ios_xr_ipv6_nd_oper/ipv6_node_discovery/nodes/node/bundle_nodes/bundle_node/ipv6_nd_bl_node_entry.proto

package cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// IPv6 node discovery bundle node information
type Ipv6NdBlNodeEntry_KEYS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeName   string `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	NodeName_1 string `protobuf:"bytes,2,opt,name=node_name_1,json=nodeName1,proto3" json:"node_name_1,omitempty"`
}

func (x *Ipv6NdBlNodeEntry_KEYS) Reset() {
	*x = Ipv6NdBlNodeEntry_KEYS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ipv6NdBlNodeEntry_KEYS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ipv6NdBlNodeEntry_KEYS) ProtoMessage() {}

func (x *Ipv6NdBlNodeEntry_KEYS) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ipv6NdBlNodeEntry_KEYS.ProtoReflect.Descriptor instead.
func (*Ipv6NdBlNodeEntry_KEYS) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_rawDescGZIP(), []int{0}
}

func (x *Ipv6NdBlNodeEntry_KEYS) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *Ipv6NdBlNodeEntry_KEYS) GetNodeName_1() string {
	if x != nil {
		return x.NodeName_1
	}
	return ""
}

type Ipv6NdBlNodeEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Group ID
	GroupId uint32 `protobuf:"varint,50,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// Process Name
	ProcessName string `protobuf:"bytes,51,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	// Uptime of node (secs)
	Age *BagTimespec `protobuf:"bytes,52,opt,name=age,proto3" json:"age,omitempty"`
	// Sent sequence num
	SentSequenceNumber uint32 `protobuf:"varint,53,opt,name=sent_sequence_number,json=sentSequenceNumber,proto3" json:"sent_sequence_number,omitempty"`
	// Received sequence num
	ReceivedSequenceNumber uint32 `protobuf:"varint,54,opt,name=received_sequence_number,json=receivedSequenceNumber,proto3" json:"received_sequence_number,omitempty"`
	// State
	State string `protobuf:"bytes,55,opt,name=state,proto3" json:"state,omitempty"`
	// State changes
	StateChanges uint32 `protobuf:"varint,56,opt,name=state_changes,json=stateChanges,proto3" json:"state_changes,omitempty"`
	// Total packet sends
	SentPackets uint32 `protobuf:"varint,57,opt,name=sent_packets,json=sentPackets,proto3" json:"sent_packets,omitempty"`
	// Total packet receives
	ReceivedPackets uint32 `protobuf:"varint,58,opt,name=received_packets,json=receivedPackets,proto3" json:"received_packets,omitempty"`
}

func (x *Ipv6NdBlNodeEntry) Reset() {
	*x = Ipv6NdBlNodeEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ipv6NdBlNodeEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ipv6NdBlNodeEntry) ProtoMessage() {}

func (x *Ipv6NdBlNodeEntry) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ipv6NdBlNodeEntry.ProtoReflect.Descriptor instead.
func (*Ipv6NdBlNodeEntry) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_rawDescGZIP(), []int{1}
}

func (x *Ipv6NdBlNodeEntry) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *Ipv6NdBlNodeEntry) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *Ipv6NdBlNodeEntry) GetAge() *BagTimespec {
	if x != nil {
		return x.Age
	}
	return nil
}

func (x *Ipv6NdBlNodeEntry) GetSentSequenceNumber() uint32 {
	if x != nil {
		return x.SentSequenceNumber
	}
	return 0
}

func (x *Ipv6NdBlNodeEntry) GetReceivedSequenceNumber() uint32 {
	if x != nil {
		return x.ReceivedSequenceNumber
	}
	return 0
}

func (x *Ipv6NdBlNodeEntry) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Ipv6NdBlNodeEntry) GetStateChanges() uint32 {
	if x != nil {
		return x.StateChanges
	}
	return 0
}

func (x *Ipv6NdBlNodeEntry) GetSentPackets() uint32 {
	if x != nil {
		return x.SentPackets
	}
	return 0
}

func (x *Ipv6NdBlNodeEntry) GetReceivedPackets() uint32 {
	if x != nil {
		return x.ReceivedPackets
	}
	return 0
}

// Timespec specifying the number of seconds since the base time of 00:00:00 GMT, 1 January 1970.
type BagTimespec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Number of seconds
	Seconds uint32 `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
}

func (x *BagTimespec) Reset() {
	*x = BagTimespec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BagTimespec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BagTimespec) ProtoMessage() {}

func (x *BagTimespec) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BagTimespec.ProtoReflect.Descriptor instead.
func (*BagTimespec) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_rawDescGZIP(), []int{2}
}

func (x *BagTimespec) GetSeconds() uint32 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

var File_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto protoreflect.FileDescriptor

var file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_rawDesc = []byte{
	0x0a, 0x6d, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f, 0x78, 0x72, 0x5f, 0x69,
	0x70, 0x76, 0x36, 0x5f, 0x6e, 0x64, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x2f, 0x69, 0x70, 0x76, 0x36,
	0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2f,
	0x6e, 0x6f, 0x64, 0x65, 0x73, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x62, 0x75, 0x6e, 0x64, 0x6c,
	0x65, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x2f, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x5f, 0x6e,
	0x6f, 0x64, 0x65, 0x2f, 0x69, 0x70, 0x76, 0x36, 0x5f, 0x6e, 0x64, 0x5f, 0x62, 0x6c, 0x5f, 0x6e,
	0x6f, 0x64, 0x65, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x51, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f, 0x78, 0x72, 0x5f, 0x69, 0x70,
	0x76, 0x36, 0x5f, 0x6e, 0x64, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x2e, 0x69, 0x70, 0x76, 0x36, 0x5f,
	0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x6e,
	0x6f, 0x64, 0x65, 0x73, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65,
	0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x2e, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x5f, 0x6e, 0x6f,
	0x64, 0x65, 0x22, 0x59, 0x0a, 0x1a, 0x69, 0x70, 0x76, 0x36, 0x5f, 0x6e, 0x64, 0x5f, 0x62, 0x6c,
	0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x4b, 0x45, 0x59, 0x53,
	0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a,
	0x0b, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x31, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x31, 0x22, 0xbd, 0x03,
	0x0a, 0x15, 0x69, 0x70, 0x76, 0x36, 0x5f, 0x6e, 0x64, 0x5f, 0x62, 0x6c, 0x5f, 0x6e, 0x6f, 0x64,
	0x65, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x5f, 0x69, 0x64, 0x18, 0x32, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x33, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x71, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x34, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x5f, 0x2e, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f, 0x78,
	0x72, 0x5f, 0x69, 0x70, 0x76, 0x36, 0x5f, 0x6e, 0x64, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x2e, 0x69,
	0x70, 0x76, 0x36, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65,
	0x72, 0x79, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x62, 0x75,
	0x6e, 0x64, 0x6c, 0x65, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x2e, 0x62, 0x75, 0x6e, 0x64, 0x6c,
	0x65, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x62, 0x61, 0x67, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x70, 0x65, 0x63, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x30, 0x0a, 0x14, 0x73, 0x65, 0x6e, 0x74,
	0x5f, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x35, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x12, 0x73, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x18, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x5f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x36, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x16, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x37, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x18, 0x38, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x12,
	0x21, 0x0a, 0x0c, 0x73, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x18,
	0x39, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x73, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x73, 0x12, 0x29, 0x0a, 0x10, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x5f, 0x70,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x18, 0x3a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x22, 0x28, 0x0a,
	0x0c, 0x62, 0x61, 0x67, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x70, 0x65, 0x63, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_rawDescOnce sync.Once
	file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_rawDescData = file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_rawDesc
)

func file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_rawDescGZIP() []byte {
	file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_rawDescOnce.Do(func() {
		file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_rawDescData = protoimpl.X.CompressGZIP(file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_rawDescData)
	})
	return file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_rawDescData
}

var file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_goTypes = []interface{}{
	(*Ipv6NdBlNodeEntry_KEYS)(nil), // 0: cisco_ios_xr_ipv6_nd_oper.ipv6_node_discovery.nodes.node.bundle_nodes.bundle_node.ipv6_nd_bl_node_entry_KEYS
	(*Ipv6NdBlNodeEntry)(nil),      // 1: cisco_ios_xr_ipv6_nd_oper.ipv6_node_discovery.nodes.node.bundle_nodes.bundle_node.ipv6_nd_bl_node_entry
	(*BagTimespec)(nil),            // 2: cisco_ios_xr_ipv6_nd_oper.ipv6_node_discovery.nodes.node.bundle_nodes.bundle_node.bag_timespec
}
var file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_depIdxs = []int32{
	2, // 0: cisco_ios_xr_ipv6_nd_oper.ipv6_node_discovery.nodes.node.bundle_nodes.bundle_node.ipv6_nd_bl_node_entry.age:type_name -> cisco_ios_xr_ipv6_nd_oper.ipv6_node_discovery.nodes.node.bundle_nodes.bundle_node.bag_timespec
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() {
	file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_init()
}
func file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_init() {
	if File_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ipv6NdBlNodeEntry_KEYS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ipv6NdBlNodeEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BagTimespec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_goTypes,
		DependencyIndexes: file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_depIdxs,
		MessageInfos:      file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_msgTypes,
	}.Build()
	File_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto = out.File
	file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_rawDesc = nil
	file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_goTypes = nil
	file_cisco_ios_xr_ipv6_nd_oper_ipv6_node_discovery_nodes_node_bundle_nodes_bundle_node_ipv6_nd_bl_node_entry_proto_depIdxs = nil
}
