// Copyright (c) 2015, Cisco Systems
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//
// 1. Redistributions of source code must retain the above copyright notice,
//    this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
// TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
// LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// This file is autogenerated
//
// The following edits are possible, without affecting the validity of the
// file:
//
//  * Fields may be renamed.
//  * Fields may be deleted.
//  * The unique numbered tag for a field may be changed, provided that
//    the ordering of tags for fields within a message is preserved.
//  * Message types may be renamed.
//  * Message types may be deleted (if all fields that reference them
//    have been deleted).
//
// All Cisco message and field extensions must be preserved (except when the
// field itself is being deleted).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: cisco_ios_xr_snmp_agent_oper/snmp/information/incoming_queue/snmp_incomingQ_stats_entry.proto

package cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// SNMP IncomingQ Stats Entry
type SnmpIncomingQStatsEntry_KEYS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SnmpIncomingQStatsEntry_KEYS) Reset() {
	*x = SnmpIncomingQStatsEntry_KEYS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnmpIncomingQStatsEntry_KEYS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnmpIncomingQStatsEntry_KEYS) ProtoMessage() {}

func (x *SnmpIncomingQStatsEntry_KEYS) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnmpIncomingQStatsEntry_KEYS.ProtoReflect.Descriptor instead.
func (*SnmpIncomingQStatsEntry_KEYS) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_rawDescGZIP(), []int{0}
}

type SnmpIncomingQStatsEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Number of NMS Queues Exist.
	QueueCount uint32 `protobuf:"varint,50,opt,name=queue_count,json=queueCount,proto3" json:"queue_count,omitempty"`
	// Each Entry Details.
	InqEntry []*SnmpInqDetail `protobuf:"bytes,51,rep,name=inq_entry,json=inqEntry,proto3" json:"inq_entry,omitempty"`
}

func (x *SnmpIncomingQStatsEntry) Reset() {
	*x = SnmpIncomingQStatsEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnmpIncomingQStatsEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnmpIncomingQStatsEntry) ProtoMessage() {}

func (x *SnmpIncomingQStatsEntry) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnmpIncomingQStatsEntry.ProtoReflect.Descriptor instead.
func (*SnmpIncomingQStatsEntry) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_rawDescGZIP(), []int{1}
}

func (x *SnmpIncomingQStatsEntry) GetQueueCount() uint32 {
	if x != nil {
		return x.QueueCount
	}
	return 0
}

func (x *SnmpIncomingQStatsEntry) GetInqEntry() []*SnmpInqDetail {
	if x != nil {
		return x.InqEntry
	}
	return nil
}

// SNMP Address Information
type SnmpInqDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Address of NMS Q
	AddressOfQueue string `protobuf:"bytes,1,opt,name=address_of_queue,json=addressOfQueue,proto3" json:"address_of_queue,omitempty"`
	// Request Count of Each Queue.
	RequestCount uint32 `protobuf:"varint,2,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
	// Processed request Count.
	ProcessedRequestCount uint32 `protobuf:"varint,3,opt,name=processed_request_count,json=processedRequestCount,proto3" json:"processed_request_count,omitempty"`
	// Last Access time of Each Queue.
	LastAccessTime string `protobuf:"bytes,4,opt,name=last_access_time,json=lastAccessTime,proto3" json:"last_access_time,omitempty"`
	// Priority of Each Queue.
	Priority uint32 `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
}

func (x *SnmpInqDetail) Reset() {
	*x = SnmpInqDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnmpInqDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnmpInqDetail) ProtoMessage() {}

func (x *SnmpInqDetail) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnmpInqDetail.ProtoReflect.Descriptor instead.
func (*SnmpInqDetail) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_rawDescGZIP(), []int{2}
}

func (x *SnmpInqDetail) GetAddressOfQueue() string {
	if x != nil {
		return x.AddressOfQueue
	}
	return ""
}

func (x *SnmpInqDetail) GetRequestCount() uint32 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *SnmpInqDetail) GetProcessedRequestCount() uint32 {
	if x != nil {
		return x.ProcessedRequestCount
	}
	return 0
}

func (x *SnmpInqDetail) GetLastAccessTime() string {
	if x != nil {
		return x.LastAccessTime
	}
	return ""
}

func (x *SnmpInqDetail) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

var File_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto protoreflect.FileDescriptor

var file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_rawDesc = []byte{
	0x0a, 0x5d, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f, 0x78, 0x72, 0x5f, 0x73,
	0x6e, 0x6d, 0x70, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x2f, 0x73,
	0x6e, 0x6d, 0x70, 0x2f, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2f, 0x73,
	0x6e, 0x6d, 0x70, 0x5f, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x51, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x73, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x3c, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f, 0x78, 0x72, 0x5f, 0x73, 0x6e,
	0x6d, 0x70, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x2e, 0x73, 0x6e,
	0x6d, 0x70, 0x2e, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x69,
	0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x22, 0x21, 0x0a,
	0x1f, 0x73, 0x6e, 0x6d, 0x70, 0x5f, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x51, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x73, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x4b, 0x45, 0x59, 0x53,
	0x22, 0xa9, 0x01, 0x0a, 0x1a, 0x73, 0x6e, 0x6d, 0x70, 0x5f, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x69,
	0x6e, 0x67, 0x51, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x1f, 0x0a, 0x0b, 0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x32,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x71, 0x75, 0x65, 0x75, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x6a, 0x0a, 0x09, 0x69, 0x6e, 0x71, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x33, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x4d, 0x2e, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f,
	0x78, 0x72, 0x5f, 0x73, 0x6e, 0x6d, 0x70, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x6f, 0x70,
	0x65, 0x72, 0x2e, 0x73, 0x6e, 0x6d, 0x70, 0x2e, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x71, 0x75, 0x65,
	0x75, 0x65, 0x2e, 0x73, 0x6e, 0x6d, 0x70, 0x5f, 0x69, 0x6e, 0x71, 0x5f, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x52, 0x08, 0x69, 0x6e, 0x71, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x22, 0xde, 0x01, 0x0a,
	0x0f, 0x73, 0x6e, 0x6d, 0x70, 0x5f, 0x69, 0x6e, 0x71, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x12, 0x28, 0x0a, 0x10, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x6f, 0x66, 0x5f, 0x71,
	0x75, 0x65, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x4f, 0x66, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x36, 0x0a, 0x17, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x15, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x5f,
	0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_rawDescOnce sync.Once
	file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_rawDescData = file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_rawDesc
)

func file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_rawDescGZIP() []byte {
	file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_rawDescOnce.Do(func() {
		file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_rawDescData = protoimpl.X.CompressGZIP(file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_rawDescData)
	})
	return file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_rawDescData
}

var file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_goTypes = []interface{}{
	(*SnmpIncomingQStatsEntry_KEYS)(nil), // 0: cisco_ios_xr_snmp_agent_oper.snmp.information.incoming_queue.snmp_incomingQ_stats_entry_KEYS
	(*SnmpIncomingQStatsEntry)(nil),      // 1: cisco_ios_xr_snmp_agent_oper.snmp.information.incoming_queue.snmp_incomingQ_stats_entry
	(*SnmpInqDetail)(nil),                // 2: cisco_ios_xr_snmp_agent_oper.snmp.information.incoming_queue.snmp_inq_detail
}
var file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_depIdxs = []int32{
	2, // 0: cisco_ios_xr_snmp_agent_oper.snmp.information.incoming_queue.snmp_incomingQ_stats_entry.inq_entry:type_name -> cisco_ios_xr_snmp_agent_oper.snmp.information.incoming_queue.snmp_inq_detail
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() {
	file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_init()
}
func file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_init() {
	if File_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnmpIncomingQStatsEntry_KEYS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnmpIncomingQStatsEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnmpInqDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_goTypes,
		DependencyIndexes: file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_depIdxs,
		MessageInfos:      file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_msgTypes,
	}.Build()
	File_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto = out.File
	file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_rawDesc = nil
	file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_goTypes = nil
	file_cisco_ios_xr_snmp_agent_oper_snmp_information_incoming_queue_snmp_incomingQ_stats_entry_proto_depIdxs = nil
}
