// Copyright (c) 2015, Cisco Systems
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//
// 1. Redistributions of source code must retain the above copyright notice,
//    this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
// TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
// LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// This file is autogenerated
//
// The following edits are possible, without affecting the validity of the
// file:
//
//  * Fields may be renamed.
//  * Fields may be deleted.
//  * The unique numbered tag for a field may be changed, provided that
//    the ordering of tags for fields within a message is preserved.
//  * Message types may be renamed.
//  * Message types may be deleted (if all fields that reference them
//    have been deleted).
//
// All Cisco message and field extensions must be preserved (except when the
// field itself is being deleted).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: cisco_ios_xr_pfi_im_cmd_oper/interfaces/interface_summary/im_if_summary_info.proto

package cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Interface summary bag
type ImIfSummaryInfo_KEYS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ImIfSummaryInfo_KEYS) Reset() {
	*x = ImIfSummaryInfo_KEYS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImIfSummaryInfo_KEYS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImIfSummaryInfo_KEYS) ProtoMessage() {}

func (x *ImIfSummaryInfo_KEYS) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImIfSummaryInfo_KEYS.ProtoReflect.Descriptor instead.
func (*ImIfSummaryInfo_KEYS) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_rawDescGZIP(), []int{0}
}

type ImIfSummaryInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of per interface type summary information
	InterfaceTypeList []*ImIfTypeSummarySt `protobuf:"bytes,50,rep,name=interface_type_list,json=interfaceTypeList,proto3" json:"interface_type_list,omitempty"`
	// Counts for all interfaces
	InterfaceCounts *ImIfGroupCountsSt `protobuf:"bytes,51,opt,name=interface_counts,json=interfaceCounts,proto3" json:"interface_counts,omitempty"`
}

func (x *ImIfSummaryInfo) Reset() {
	*x = ImIfSummaryInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImIfSummaryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImIfSummaryInfo) ProtoMessage() {}

func (x *ImIfSummaryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImIfSummaryInfo.ProtoReflect.Descriptor instead.
func (*ImIfSummaryInfo) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_rawDescGZIP(), []int{1}
}

func (x *ImIfSummaryInfo) GetInterfaceTypeList() []*ImIfTypeSummarySt {
	if x != nil {
		return x.InterfaceTypeList
	}
	return nil
}

func (x *ImIfSummaryInfo) GetInterfaceCounts() *ImIfGroupCountsSt {
	if x != nil {
		return x.InterfaceCounts
	}
	return nil
}

type ImIfGroupCountsSt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Number of interfaces
	InterfaceCount uint32 `protobuf:"varint,1,opt,name=interface_count,json=interfaceCount,proto3" json:"interface_count,omitempty"`
	// Number of interfaces in UP state
	UpInterfaceCount uint32 `protobuf:"varint,2,opt,name=up_interface_count,json=upInterfaceCount,proto3" json:"up_interface_count,omitempty"`
	// Number of interfaces in DOWN state
	DownInterfaceCount uint32 `protobuf:"varint,3,opt,name=down_interface_count,json=downInterfaceCount,proto3" json:"down_interface_count,omitempty"`
	// Number of interfaces in an ADMINDOWN state
	AdminDownInterfaceCount uint32 `protobuf:"varint,4,opt,name=admin_down_interface_count,json=adminDownInterfaceCount,proto3" json:"admin_down_interface_count,omitempty"`
}

func (x *ImIfGroupCountsSt) Reset() {
	*x = ImIfGroupCountsSt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImIfGroupCountsSt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImIfGroupCountsSt) ProtoMessage() {}

func (x *ImIfGroupCountsSt) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImIfGroupCountsSt.ProtoReflect.Descriptor instead.
func (*ImIfGroupCountsSt) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_rawDescGZIP(), []int{2}
}

func (x *ImIfGroupCountsSt) GetInterfaceCount() uint32 {
	if x != nil {
		return x.InterfaceCount
	}
	return 0
}

func (x *ImIfGroupCountsSt) GetUpInterfaceCount() uint32 {
	if x != nil {
		return x.UpInterfaceCount
	}
	return 0
}

func (x *ImIfGroupCountsSt) GetDownInterfaceCount() uint32 {
	if x != nil {
		return x.DownInterfaceCount
	}
	return 0
}

func (x *ImIfGroupCountsSt) GetAdminDownInterfaceCount() uint32 {
	if x != nil {
		return x.AdminDownInterfaceCount
	}
	return 0
}

type ImIfTypeSummarySt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name of the interface type
	InterfaceTypeName string `protobuf:"bytes,1,opt,name=interface_type_name,json=interfaceTypeName,proto3" json:"interface_type_name,omitempty"`
	// Description of the interface type
	InterfaceTypeDescription string `protobuf:"bytes,2,opt,name=interface_type_description,json=interfaceTypeDescription,proto3" json:"interface_type_description,omitempty"`
	// Counts for interfaces of this type
	InterfaceCounts *ImIfGroupCountsSt `protobuf:"bytes,3,opt,name=interface_counts,json=interfaceCounts,proto3" json:"interface_counts,omitempty"`
}

func (x *ImIfTypeSummarySt) Reset() {
	*x = ImIfTypeSummarySt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImIfTypeSummarySt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImIfTypeSummarySt) ProtoMessage() {}

func (x *ImIfTypeSummarySt) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImIfTypeSummarySt.ProtoReflect.Descriptor instead.
func (*ImIfTypeSummarySt) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_rawDescGZIP(), []int{3}
}

func (x *ImIfTypeSummarySt) GetInterfaceTypeName() string {
	if x != nil {
		return x.InterfaceTypeName
	}
	return ""
}

func (x *ImIfTypeSummarySt) GetInterfaceTypeDescription() string {
	if x != nil {
		return x.InterfaceTypeDescription
	}
	return ""
}

func (x *ImIfTypeSummarySt) GetInterfaceCounts() *ImIfGroupCountsSt {
	if x != nil {
		return x.InterfaceCounts
	}
	return nil
}

var File_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto protoreflect.FileDescriptor

var file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_rawDesc = []byte{
	0x0a, 0x52, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f, 0x78, 0x72, 0x5f, 0x70,
	0x66, 0x69, 0x5f, 0x69, 0x6d, 0x5f, 0x63, 0x6d, 0x64, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x2f, 0x69, 0x6d, 0x5f, 0x69,
	0x66, 0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x39, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f,
	0x78, 0x72, 0x5f, 0x70, 0x66, 0x69, 0x5f, 0x69, 0x6d, 0x5f, 0x63, 0x6d, 0x64, 0x5f, 0x6f, 0x70,
	0x65, 0x72, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x2e, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x22,
	0x19, 0x0a, 0x17, 0x69, 0x6d, 0x5f, 0x69, 0x66, 0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x4b, 0x45, 0x59, 0x53, 0x22, 0x94, 0x02, 0x0a, 0x12, 0x69,
	0x6d, 0x5f, 0x69, 0x66, 0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x12, 0x80, 0x01, 0x0a, 0x13, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x32, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x50, 0x2e, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f, 0x78, 0x72, 0x5f, 0x70,
	0x66, 0x69, 0x5f, 0x69, 0x6d, 0x5f, 0x63, 0x6d, 0x64, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x2e, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x2e, 0x69, 0x6d, 0x5f, 0x69,
	0x66, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x73,
	0x74, 0x52, 0x11, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x7b, 0x0a, 0x10, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x33, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x50,
	0x2e, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f, 0x78, 0x72, 0x5f, 0x70, 0x66,
	0x69, 0x5f, 0x69, 0x6d, 0x5f, 0x63, 0x6d, 0x64, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x2e, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x2e, 0x69, 0x6d, 0x5f, 0x69, 0x66,
	0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x5f, 0x73, 0x74,
	0x52, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x73, 0x22, 0xdd, 0x01, 0x0a, 0x15, 0x69, 0x6d, 0x5f, 0x69, 0x66, 0x5f, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x5f, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2c, 0x0a, 0x12, 0x75, 0x70, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x10, 0x75, 0x70, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x30, 0x0a, 0x14, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x12, 0x64, 0x6f, 0x77, 0x6e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x3b, 0x0a, 0x1a, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x64, 0x6f,
	0x77, 0x6e, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x17, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x44,
	0x6f, 0x77, 0x6e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x82, 0x02, 0x0a, 0x15, 0x69, 0x6d, 0x5f, 0x69, 0x66, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x13, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3c, 0x0a, 0x1a, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x18, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x7b, 0x0a, 0x10, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x50, 0x2e, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f,
	0x78, 0x72, 0x5f, 0x70, 0x66, 0x69, 0x5f, 0x69, 0x6d, 0x5f, 0x63, 0x6d, 0x64, 0x5f, 0x6f, 0x70,
	0x65, 0x72, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x2e, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x2e,
	0x69, 0x6d, 0x5f, 0x69, 0x66, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x73, 0x5f, 0x73, 0x74, 0x52, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_rawDescOnce sync.Once
	file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_rawDescData = file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_rawDesc
)

func file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_rawDescGZIP() []byte {
	file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_rawDescOnce.Do(func() {
		file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_rawDescData)
	})
	return file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_rawDescData
}

var file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_goTypes = []interface{}{
	(*ImIfSummaryInfo_KEYS)(nil), // 0: cisco_ios_xr_pfi_im_cmd_oper.interfaces.interface_summary.im_if_summary_info_KEYS
	(*ImIfSummaryInfo)(nil),      // 1: cisco_ios_xr_pfi_im_cmd_oper.interfaces.interface_summary.im_if_summary_info
	(*ImIfGroupCountsSt)(nil),    // 2: cisco_ios_xr_pfi_im_cmd_oper.interfaces.interface_summary.im_if_group_counts_st
	(*ImIfTypeSummarySt)(nil),    // 3: cisco_ios_xr_pfi_im_cmd_oper.interfaces.interface_summary.im_if_type_summary_st
}
var file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_depIdxs = []int32{
	3, // 0: cisco_ios_xr_pfi_im_cmd_oper.interfaces.interface_summary.im_if_summary_info.interface_type_list:type_name -> cisco_ios_xr_pfi_im_cmd_oper.interfaces.interface_summary.im_if_type_summary_st
	2, // 1: cisco_ios_xr_pfi_im_cmd_oper.interfaces.interface_summary.im_if_summary_info.interface_counts:type_name -> cisco_ios_xr_pfi_im_cmd_oper.interfaces.interface_summary.im_if_group_counts_st
	2, // 2: cisco_ios_xr_pfi_im_cmd_oper.interfaces.interface_summary.im_if_type_summary_st.interface_counts:type_name -> cisco_ios_xr_pfi_im_cmd_oper.interfaces.interface_summary.im_if_group_counts_st
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() {
	file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_init()
}
func file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_init() {
	if File_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImIfSummaryInfo_KEYS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImIfSummaryInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImIfGroupCountsSt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImIfTypeSummarySt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_goTypes,
		DependencyIndexes: file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_depIdxs,
		MessageInfos:      file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_msgTypes,
	}.Build()
	File_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto = out.File
	file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_rawDesc = nil
	file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_goTypes = nil
	file_cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary_im_if_summary_info_proto_depIdxs = nil
}
