// Copyright (c) 2015, Cisco Systems
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//
// 1. Redistributions of source code must retain the above copyright notice,
//    this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
// TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
// LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// This file is autogenerated
//
// The following edits are possible, without affecting the validity of the
// file:
//
//  * Fields may be renamed.
//  * Fields may be deleted.
//  * The unique numbered tag for a field may be changed, provided that
//    the ordering of tags for fields within a message is preserved.
//  * Message types may be renamed.
//  * Message types may be deleted (if all fields that reference them
//    have been deleted).
//
// All Cisco message and field extensions must be preserved (except when the
// field itself is being deleted).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: cisco_ios_xr_fib_common_oper/fib/nodes/node/protocols/protocol/external_summary_all/fib_sh_tbl_ext_sum_all.proto

package cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// FIB external brief summary information across all clients
type FibShTblExtSumAll_KEYS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeName     string `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	ProtocolName string `protobuf:"bytes,2,opt,name=protocol_name,json=protocolName,proto3" json:"protocol_name,omitempty"`
}

func (x *FibShTblExtSumAll_KEYS) Reset() {
	*x = FibShTblExtSumAll_KEYS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FibShTblExtSumAll_KEYS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FibShTblExtSumAll_KEYS) ProtoMessage() {}

func (x *FibShTblExtSumAll_KEYS) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FibShTblExtSumAll_KEYS.ProtoReflect.Descriptor instead.
func (*FibShTblExtSumAll_KEYS) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_rawDescGZIP(), []int{0}
}

func (x *FibShTblExtSumAll_KEYS) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *FibShTblExtSumAll_KEYS) GetProtocolName() string {
	if x != nil {
		return x.ProtocolName
	}
	return ""
}

type FibShTblExtSumAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Client information
	SesaNumClient uint32 `protobuf:"varint,50,opt,name=sesa_num_client,json=sesaNumClient,proto3" json:"sesa_num_client,omitempty"`
	// External pathlist summary
	SesaPlSum *FibShTblExtPlSum `protobuf:"bytes,51,opt,name=sesa_pl_sum,json=sesaPlSum,proto3" json:"sesa_pl_sum,omitempty"`
}

func (x *FibShTblExtSumAll) Reset() {
	*x = FibShTblExtSumAll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FibShTblExtSumAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FibShTblExtSumAll) ProtoMessage() {}

func (x *FibShTblExtSumAll) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FibShTblExtSumAll.ProtoReflect.Descriptor instead.
func (*FibShTblExtSumAll) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_rawDescGZIP(), []int{1}
}

func (x *FibShTblExtSumAll) GetSesaNumClient() uint32 {
	if x != nil {
		return x.SesaNumClient
	}
	return 0
}

func (x *FibShTblExtSumAll) GetSesaPlSum() *FibShTblExtPlSum {
	if x != nil {
		return x.SesaPlSum
	}
	return nil
}

// FIB external client pathlist summary
type FibShTblExtPlSum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Number of ECD pathlists
	SepNumEcdPathlist uint32 `protobuf:"varint,1,opt,name=sep_num_ecd_pathlist,json=sepNumEcdPathlist,proto3" json:"sep_num_ecd_pathlist,omitempty"`
	// Number of ECD pathlists unresolved
	SepNumEcdPlUnresolved uint32 `protobuf:"varint,2,opt,name=sep_num_ecd_pl_unresolved,json=sepNumEcdPlUnresolved,proto3" json:"sep_num_ecd_pl_unresolved,omitempty"`
	// Number of ECD pathlists per interest
	SepNumEcdPlPerInterest []uint32 `protobuf:"varint,3,rep,packed,name=sep_num_ecd_pl_per_interest,json=sepNumEcdPlPerInterest,proto3" json:"sep_num_ecd_pl_per_interest,omitempty"`
}

func (x *FibShTblExtPlSum) Reset() {
	*x = FibShTblExtPlSum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FibShTblExtPlSum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FibShTblExtPlSum) ProtoMessage() {}

func (x *FibShTblExtPlSum) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FibShTblExtPlSum.ProtoReflect.Descriptor instead.
func (*FibShTblExtPlSum) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_rawDescGZIP(), []int{2}
}

func (x *FibShTblExtPlSum) GetSepNumEcdPathlist() uint32 {
	if x != nil {
		return x.SepNumEcdPathlist
	}
	return 0
}

func (x *FibShTblExtPlSum) GetSepNumEcdPlUnresolved() uint32 {
	if x != nil {
		return x.SepNumEcdPlUnresolved
	}
	return 0
}

func (x *FibShTblExtPlSum) GetSepNumEcdPlPerInterest() []uint32 {
	if x != nil {
		return x.SepNumEcdPlPerInterest
	}
	return nil
}

var File_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto protoreflect.FileDescriptor

var file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_rawDesc = []byte{
	0x0a, 0x70, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f, 0x78, 0x72, 0x5f, 0x66,
	0x69, 0x62, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x2f, 0x66,
	0x69, 0x62, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2f, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x5f, 0x61, 0x6c, 0x6c, 0x2f, 0x66, 0x69, 0x62, 0x5f, 0x73, 0x68, 0x5f, 0x74, 0x62, 0x6c,
	0x5f, 0x65, 0x78, 0x74, 0x5f, 0x73, 0x75, 0x6d, 0x5f, 0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x53, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f, 0x78, 0x72,
	0x5f, 0x66, 0x69, 0x62, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x6f, 0x70, 0x65, 0x72,
	0x2e, 0x66, 0x69, 0x62, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x73, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x79, 0x5f, 0x61, 0x6c, 0x6c, 0x22, 0x5f, 0x0a, 0x1b, 0x66, 0x69, 0x62, 0x5f, 0x73,
	0x68, 0x5f, 0x74, 0x62, 0x6c, 0x5f, 0x65, 0x78, 0x74, 0x5f, 0x73, 0x75, 0x6d, 0x5f, 0x61, 0x6c,
	0x6c, 0x5f, 0x4b, 0x45, 0x59, 0x53, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xcd, 0x01, 0x0a, 0x16, 0x66, 0x69, 0x62,
	0x5f, 0x73, 0x68, 0x5f, 0x74, 0x62, 0x6c, 0x5f, 0x65, 0x78, 0x74, 0x5f, 0x73, 0x75, 0x6d, 0x5f,
	0x61, 0x6c, 0x6c, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x65, 0x73, 0x61, 0x5f, 0x6e, 0x75, 0x6d, 0x5f,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x32, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x73, 0x65,
	0x73, 0x61, 0x4e, 0x75, 0x6d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x8a, 0x01, 0x0a, 0x0b,
	0x73, 0x65, 0x73, 0x61, 0x5f, 0x70, 0x6c, 0x5f, 0x73, 0x75, 0x6d, 0x18, 0x33, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x6a, 0x2e, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f, 0x78, 0x72,
	0x5f, 0x66, 0x69, 0x62, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x6f, 0x70, 0x65, 0x72,
	0x2e, 0x66, 0x69, 0x62, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x73, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x79, 0x5f, 0x61, 0x6c, 0x6c, 0x2e, 0x66, 0x69, 0x62, 0x5f, 0x73, 0x68, 0x5f, 0x74,
	0x62, 0x6c, 0x5f, 0x65, 0x78, 0x74, 0x5f, 0x70, 0x6c, 0x5f, 0x73, 0x75, 0x6d, 0x52, 0x09, 0x73,
	0x65, 0x73, 0x61, 0x50, 0x6c, 0x53, 0x75, 0x6d, 0x22, 0xbf, 0x01, 0x0a, 0x15, 0x66, 0x69, 0x62,
	0x5f, 0x73, 0x68, 0x5f, 0x74, 0x62, 0x6c, 0x5f, 0x65, 0x78, 0x74, 0x5f, 0x70, 0x6c, 0x5f, 0x73,
	0x75, 0x6d, 0x12, 0x2f, 0x0a, 0x14, 0x73, 0x65, 0x70, 0x5f, 0x6e, 0x75, 0x6d, 0x5f, 0x65, 0x63,
	0x64, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x11, 0x73, 0x65, 0x70, 0x4e, 0x75, 0x6d, 0x45, 0x63, 0x64, 0x50, 0x61, 0x74, 0x68, 0x6c,
	0x69, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x19, 0x73, 0x65, 0x70, 0x5f, 0x6e, 0x75, 0x6d, 0x5f, 0x65,
	0x63, 0x64, 0x5f, 0x70, 0x6c, 0x5f, 0x75, 0x6e, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x15, 0x73, 0x65, 0x70, 0x4e, 0x75, 0x6d, 0x45, 0x63,
	0x64, 0x50, 0x6c, 0x55, 0x6e, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x12, 0x3b, 0x0a,
	0x1b, 0x73, 0x65, 0x70, 0x5f, 0x6e, 0x75, 0x6d, 0x5f, 0x65, 0x63, 0x64, 0x5f, 0x70, 0x6c, 0x5f,
	0x70, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0d, 0x52, 0x16, 0x73, 0x65, 0x70, 0x4e, 0x75, 0x6d, 0x45, 0x63, 0x64, 0x50, 0x6c, 0x50,
	0x65, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_rawDescOnce sync.Once
	file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_rawDescData = file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_rawDesc
)

func file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_rawDescGZIP() []byte {
	file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_rawDescOnce.Do(func() {
		file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_rawDescData = protoimpl.X.CompressGZIP(file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_rawDescData)
	})
	return file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_rawDescData
}

var file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_goTypes = []interface{}{
	(*FibShTblExtSumAll_KEYS)(nil), // 0: cisco_ios_xr_fib_common_oper.fib.nodes.node.protocols.protocol.external_summary_all.fib_sh_tbl_ext_sum_all_KEYS
	(*FibShTblExtSumAll)(nil),      // 1: cisco_ios_xr_fib_common_oper.fib.nodes.node.protocols.protocol.external_summary_all.fib_sh_tbl_ext_sum_all
	(*FibShTblExtPlSum)(nil),       // 2: cisco_ios_xr_fib_common_oper.fib.nodes.node.protocols.protocol.external_summary_all.fib_sh_tbl_ext_pl_sum
}
var file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_depIdxs = []int32{
	2, // 0: cisco_ios_xr_fib_common_oper.fib.nodes.node.protocols.protocol.external_summary_all.fib_sh_tbl_ext_sum_all.sesa_pl_sum:type_name -> cisco_ios_xr_fib_common_oper.fib.nodes.node.protocols.protocol.external_summary_all.fib_sh_tbl_ext_pl_sum
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() {
	file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_init()
}
func file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_init() {
	if File_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FibShTblExtSumAll_KEYS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FibShTblExtSumAll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FibShTblExtPlSum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_goTypes,
		DependencyIndexes: file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_depIdxs,
		MessageInfos:      file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_msgTypes,
	}.Build()
	File_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto = out.File
	file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_rawDesc = nil
	file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_goTypes = nil
	file_cisco_ios_xr_fib_common_oper_fib_nodes_node_protocols_protocol_external_summary_all_fib_sh_tbl_ext_sum_all_proto_depIdxs = nil
}
