// Copyright (c) 2015, Cisco Systems
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//
// 1. Redistributions of source code must retain the above copyright notice,
//    this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
// TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
// LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// This file is autogenerated
//
// The following edits are possible, without affecting the validity of the
// file:
//
//  * Fields may be renamed.
//  * Fields may be deleted.
//  * The unique numbered tag for a field may be changed, provided that
//    the ordering of tags for fields within a message is preserved.
//  * Message types may be renamed.
//  * Message types may be deleted (if all fields that reference them
//    have been deleted).
//
// All Cisco message and field extensions must be preserved (except when the
// field itself is being deleted).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: cisco_ios_xr_ipv6_ma_oper/ipv6_network/nodes/node/interface_data/summary/ipv6_if_summary.proto

package cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Summary info of IPv6 interfaces
type Ipv6IfSummary_KEYS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeName string `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
}

func (x *Ipv6IfSummary_KEYS) Reset() {
	*x = Ipv6IfSummary_KEYS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ipv6IfSummary_KEYS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ipv6IfSummary_KEYS) ProtoMessage() {}

func (x *Ipv6IfSummary_KEYS) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ipv6IfSummary_KEYS.ProtoReflect.Descriptor instead.
func (*Ipv6IfSummary_KEYS) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_rawDescGZIP(), []int{0}
}

func (x *Ipv6IfSummary_KEYS) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type Ipv6IfSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Number of interfaces (up,up)
	IfUpUp *IfSummaryT `protobuf:"bytes,50,opt,name=if_up_up,json=ifUpUp,proto3" json:"if_up_up,omitempty"`
	// Number of interfaces (up,down)
	IfUpDown *IfSummaryT `protobuf:"bytes,51,opt,name=if_up_down,json=ifUpDown,proto3" json:"if_up_down,omitempty"`
	// Number of interfaces (down,down)
	IfDownDown *IfSummaryT `protobuf:"bytes,52,opt,name=if_down_down,json=ifDownDown,proto3" json:"if_down_down,omitempty"`
	// Number of interfaces (shutdown,down)
	IfShutdownDown *IfSummaryT `protobuf:"bytes,53,opt,name=if_shutdown_down,json=ifShutdownDown,proto3" json:"if_shutdown_down,omitempty"`
	// Number of interfaces (up,down) with basecaps up
	IfUpDownBasecapsUp uint32 `protobuf:"varint,54,opt,name=if_up_down_basecaps_up,json=ifUpDownBasecapsUp,proto3" json:"if_up_down_basecaps_up,omitempty"`
}

func (x *Ipv6IfSummary) Reset() {
	*x = Ipv6IfSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ipv6IfSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ipv6IfSummary) ProtoMessage() {}

func (x *Ipv6IfSummary) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ipv6IfSummary.ProtoReflect.Descriptor instead.
func (*Ipv6IfSummary) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_rawDescGZIP(), []int{1}
}

func (x *Ipv6IfSummary) GetIfUpUp() *IfSummaryT {
	if x != nil {
		return x.IfUpUp
	}
	return nil
}

func (x *Ipv6IfSummary) GetIfUpDown() *IfSummaryT {
	if x != nil {
		return x.IfUpDown
	}
	return nil
}

func (x *Ipv6IfSummary) GetIfDownDown() *IfSummaryT {
	if x != nil {
		return x.IfDownDown
	}
	return nil
}

func (x *Ipv6IfSummary) GetIfShutdownDown() *IfSummaryT {
	if x != nil {
		return x.IfShutdownDown
	}
	return nil
}

func (x *Ipv6IfSummary) GetIfUpDownBasecapsUp() uint32 {
	if x != nil {
		return x.IfUpDownBasecapsUp
	}
	return 0
}

// Count of assigned/unnumbered interfaces
type IfSummaryT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Number of interfaces with explicit addresses
	IpAssigned uint32 `protobuf:"varint,1,opt,name=ip_assigned,json=ipAssigned,proto3" json:"ip_assigned,omitempty"`
	// Number of unnumbered interfaces with explicit addresses
	IpUnnumbered uint32 `protobuf:"varint,2,opt,name=ip_unnumbered,json=ipUnnumbered,proto3" json:"ip_unnumbered,omitempty"`
	// Number of unassigned interfaces without explicit address
	IpUnassigned uint32 `protobuf:"varint,3,opt,name=ip_unassigned,json=ipUnassigned,proto3" json:"ip_unassigned,omitempty"`
}

func (x *IfSummaryT) Reset() {
	*x = IfSummaryT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IfSummaryT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IfSummaryT) ProtoMessage() {}

func (x *IfSummaryT) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IfSummaryT.ProtoReflect.Descriptor instead.
func (*IfSummaryT) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_rawDescGZIP(), []int{2}
}

func (x *IfSummaryT) GetIpAssigned() uint32 {
	if x != nil {
		return x.IpAssigned
	}
	return 0
}

func (x *IfSummaryT) GetIpUnnumbered() uint32 {
	if x != nil {
		return x.IpUnnumbered
	}
	return 0
}

func (x *IfSummaryT) GetIpUnassigned() uint32 {
	if x != nil {
		return x.IpUnassigned
	}
	return 0
}

var File_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto protoreflect.FileDescriptor

var file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_rawDesc = []byte{
	0x0a, 0x5e, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f, 0x78, 0x72, 0x5f, 0x69,
	0x70, 0x76, 0x36, 0x5f, 0x6d, 0x61, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x2f, 0x69, 0x70, 0x76, 0x36,
	0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x2f, 0x6e,
	0x6f, 0x64, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x2f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x2f, 0x69, 0x70, 0x76, 0x36, 0x5f,
	0x69, 0x66, 0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x48, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f, 0x78, 0x72, 0x5f, 0x69,
	0x70, 0x76, 0x36, 0x5f, 0x6d, 0x61, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x2e, 0x69, 0x70, 0x76, 0x36,
	0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x2e, 0x6e,
	0x6f, 0x64, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x22, 0x33, 0x0a, 0x14, 0x69, 0x70,
	0x76, 0x36, 0x5f, 0x69, 0x66, 0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x4b, 0x45,
	0x59, 0x53, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0xaa, 0x04, 0x0a, 0x0f, 0x69, 0x70, 0x76, 0x36, 0x5f, 0x69, 0x66, 0x5f, 0x73, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x79, 0x12, 0x70, 0x0a, 0x08, 0x69, 0x66, 0x5f, 0x75, 0x70, 0x5f, 0x75, 0x70, 0x18,
	0x32, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x56, 0x2e, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f,
	0x73, 0x5f, 0x78, 0x72, 0x5f, 0x69, 0x70, 0x76, 0x36, 0x5f, 0x6d, 0x61, 0x5f, 0x6f, 0x70, 0x65,
	0x72, 0x2e, 0x69, 0x70, 0x76, 0x36, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6e,
	0x6f, 0x64, 0x65, 0x73, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x2e, 0x69, 0x66, 0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x74, 0x52, 0x06, 0x69,
	0x66, 0x55, 0x70, 0x55, 0x70, 0x12, 0x74, 0x0a, 0x0a, 0x69, 0x66, 0x5f, 0x75, 0x70, 0x5f, 0x64,
	0x6f, 0x77, 0x6e, 0x18, 0x33, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x56, 0x2e, 0x63, 0x69, 0x73, 0x63,
	0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f, 0x78, 0x72, 0x5f, 0x69, 0x70, 0x76, 0x36, 0x5f, 0x6d, 0x61,
	0x5f, 0x6f, 0x70, 0x65, 0x72, 0x2e, 0x69, 0x70, 0x76, 0x36, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x73, 0x75, 0x6d,
	0x6d, 0x61, 0x72, 0x79, 0x2e, 0x69, 0x66, 0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x5f,
	0x74, 0x52, 0x08, 0x69, 0x66, 0x55, 0x70, 0x44, 0x6f, 0x77, 0x6e, 0x12, 0x78, 0x0a, 0x0c, 0x69,
	0x66, 0x5f, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x64, 0x6f, 0x77, 0x6e, 0x18, 0x34, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x56, 0x2e, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f, 0x78, 0x72,
	0x5f, 0x69, 0x70, 0x76, 0x36, 0x5f, 0x6d, 0x61, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x2e, 0x69, 0x70,
	0x76, 0x36, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x73,
	0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x2e, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x2e, 0x69, 0x66, 0x5f,
	0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x74, 0x52, 0x0a, 0x69, 0x66, 0x44, 0x6f, 0x77,
	0x6e, 0x44, 0x6f, 0x77, 0x6e, 0x12, 0x80, 0x01, 0x0a, 0x10, 0x69, 0x66, 0x5f, 0x73, 0x68, 0x75,
	0x74, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x64, 0x6f, 0x77, 0x6e, 0x18, 0x35, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x56, 0x2e, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f, 0x78, 0x72, 0x5f,
	0x69, 0x70, 0x76, 0x36, 0x5f, 0x6d, 0x61, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x2e, 0x69, 0x70, 0x76,
	0x36, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x2e,
	0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x2e, 0x69, 0x66, 0x5f, 0x73,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x74, 0x52, 0x0e, 0x69, 0x66, 0x53, 0x68, 0x75, 0x74,
	0x64, 0x6f, 0x77, 0x6e, 0x44, 0x6f, 0x77, 0x6e, 0x12, 0x32, 0x0a, 0x16, 0x69, 0x66, 0x5f, 0x75,
	0x70, 0x5f, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x63, 0x61, 0x70, 0x73, 0x5f,
	0x75, 0x70, 0x18, 0x36, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x12, 0x69, 0x66, 0x55, 0x70, 0x44, 0x6f,
	0x77, 0x6e, 0x42, 0x61, 0x73, 0x65, 0x63, 0x61, 0x70, 0x73, 0x55, 0x70, 0x22, 0x79, 0x0a, 0x0c,
	0x69, 0x66, 0x5f, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x74, 0x12, 0x1f, 0x0a, 0x0b,
	0x69, 0x70, 0x5f, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x69, 0x70, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x12, 0x23, 0x0a,
	0x0d, 0x69, 0x70, 0x5f, 0x75, 0x6e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x65, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x69, 0x70, 0x55, 0x6e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x70, 0x5f, 0x75, 0x6e, 0x61, 0x73, 0x73, 0x69, 0x67,
	0x6e, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x69, 0x70, 0x55, 0x6e, 0x61,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_rawDescOnce sync.Once
	file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_rawDescData = file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_rawDesc
)

func file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_rawDescGZIP() []byte {
	file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_rawDescOnce.Do(func() {
		file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_rawDescData = protoimpl.X.CompressGZIP(file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_rawDescData)
	})
	return file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_rawDescData
}

var file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_goTypes = []interface{}{
	(*Ipv6IfSummary_KEYS)(nil), // 0: cisco_ios_xr_ipv6_ma_oper.ipv6_network.nodes.node.interface_data.summary.ipv6_if_summary_KEYS
	(*Ipv6IfSummary)(nil),      // 1: cisco_ios_xr_ipv6_ma_oper.ipv6_network.nodes.node.interface_data.summary.ipv6_if_summary
	(*IfSummaryT)(nil),         // 2: cisco_ios_xr_ipv6_ma_oper.ipv6_network.nodes.node.interface_data.summary.if_summary_t
}
var file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_depIdxs = []int32{
	2, // 0: cisco_ios_xr_ipv6_ma_oper.ipv6_network.nodes.node.interface_data.summary.ipv6_if_summary.if_up_up:type_name -> cisco_ios_xr_ipv6_ma_oper.ipv6_network.nodes.node.interface_data.summary.if_summary_t
	2, // 1: cisco_ios_xr_ipv6_ma_oper.ipv6_network.nodes.node.interface_data.summary.ipv6_if_summary.if_up_down:type_name -> cisco_ios_xr_ipv6_ma_oper.ipv6_network.nodes.node.interface_data.summary.if_summary_t
	2, // 2: cisco_ios_xr_ipv6_ma_oper.ipv6_network.nodes.node.interface_data.summary.ipv6_if_summary.if_down_down:type_name -> cisco_ios_xr_ipv6_ma_oper.ipv6_network.nodes.node.interface_data.summary.if_summary_t
	2, // 3: cisco_ios_xr_ipv6_ma_oper.ipv6_network.nodes.node.interface_data.summary.ipv6_if_summary.if_shutdown_down:type_name -> cisco_ios_xr_ipv6_ma_oper.ipv6_network.nodes.node.interface_data.summary.if_summary_t
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() {
	file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_init()
}
func file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_init() {
	if File_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ipv6IfSummary_KEYS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ipv6IfSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IfSummaryT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_goTypes,
		DependencyIndexes: file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_depIdxs,
		MessageInfos:      file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_msgTypes,
	}.Build()
	File_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto = out.File
	file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_rawDesc = nil
	file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_goTypes = nil
	file_cisco_ios_xr_ipv6_ma_oper_ipv6_network_nodes_node_interface_data_summary_ipv6_if_summary_proto_depIdxs = nil
}
