// Copyright (c) 2015, Cisco Systems
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//
// 1. Redistributions of source code must retain the above copyright notice,
//    this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
// TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
// LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// This file is autogenerated
//
// The following edits are possible, without affecting the validity of the
// file:
//
//  * Fields may be renamed.
//  * Fields may be deleted.
//  * The unique numbered tag for a field may be changed, provided that
//    the ordering of tags for fields within a message is preserved.
//  * Message types may be renamed.
//  * Message types may be deleted (if all fields that reference them
//    have been deleted).
//
// All Cisco message and field extensions must be preserved (except when the
// field itself is being deleted).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: cisco_ios_xr_clns_isis_oper/isis/instances/instance/levels/level/database_log/isis_sh_lsp_db_log_struc.proto

package cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// LSP Database Log
type IsisShLspDbLogStruc_KEYS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceName string `protobuf:"bytes,1,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	Level        string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *IsisShLspDbLogStruc_KEYS) Reset() {
	*x = IsisShLspDbLogStruc_KEYS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsisShLspDbLogStruc_KEYS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsisShLspDbLogStruc_KEYS) ProtoMessage() {}

func (x *IsisShLspDbLogStruc_KEYS) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsisShLspDbLogStruc_KEYS.ProtoReflect.Descriptor instead.
func (*IsisShLspDbLogStruc_KEYS) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_rawDescGZIP(), []int{0}
}

func (x *IsisShLspDbLogStruc_KEYS) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *IsisShLspDbLogStruc_KEYS) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type IsisShLspDbLogStruc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Entries
	LogEntry []*IsisShLspDbLogEnt `protobuf:"bytes,50,rep,name=log_entry,json=logEntry,proto3" json:"log_entry,omitempty"`
}

func (x *IsisShLspDbLogStruc) Reset() {
	*x = IsisShLspDbLogStruc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsisShLspDbLogStruc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsisShLspDbLogStruc) ProtoMessage() {}

func (x *IsisShLspDbLogStruc) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsisShLspDbLogStruc.ProtoReflect.Descriptor instead.
func (*IsisShLspDbLogStruc) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_rawDescGZIP(), []int{1}
}

func (x *IsisShLspDbLogStruc) GetLogEntry() []*IsisShLspDbLogEnt {
	if x != nil {
		return x.LogEntry
	}
	return nil
}

// Timestamp for an event
type IsisShTimestampType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Timestamp value (seconds)
	Seconds uint32 `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	// Timestamp value (nanoseconds)
	NanoSeconds uint32 `protobuf:"varint,2,opt,name=nano_seconds,json=nanoSeconds,proto3" json:"nano_seconds,omitempty"`
}

func (x *IsisShTimestampType) Reset() {
	*x = IsisShTimestampType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsisShTimestampType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsisShTimestampType) ProtoMessage() {}

func (x *IsisShTimestampType) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsisShTimestampType.ProtoReflect.Descriptor instead.
func (*IsisShTimestampType) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_rawDescGZIP(), []int{2}
}

func (x *IsisShTimestampType) GetSeconds() uint32 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *IsisShTimestampType) GetNanoSeconds() uint32 {
	if x != nil {
		return x.NanoSeconds
	}
	return 0
}

// Generic portion of a log entry
type IsisShGenericLogEnt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Time in UTC relative to Jan 1st, 1970
	Timestamp *IsisShTimestampType `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *IsisShGenericLogEnt) Reset() {
	*x = IsisShGenericLogEnt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsisShGenericLogEnt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsisShGenericLogEnt) ProtoMessage() {}

func (x *IsisShGenericLogEnt) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsisShGenericLogEnt.ProtoReflect.Descriptor instead.
func (*IsisShGenericLogEnt) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_rawDescGZIP(), []int{3}
}

func (x *IsisShGenericLogEnt) GetTimestamp() *IsisShTimestampType {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Contents of an IS-IS LSP header
type IsisShLspHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The LSP ID
	LspId string `protobuf:"bytes,1,opt,name=lsp_id,json=lspId,proto3" json:"lsp_id,omitempty"`
	// TRUE if this is a locally generated LSP
	LocalLspFlag bool `protobuf:"varint,2,opt,name=local_lsp_flag,json=localLspFlag,proto3" json:"local_lsp_flag,omitempty"`
	// TRUE if this LSP has not expired
	LspActiveFlag bool `protobuf:"varint,3,opt,name=lsp_active_flag,json=lspActiveFlag,proto3" json:"lsp_active_flag,omitempty"`
	// Time, in seconds, until LSP expiry (if active) or deletion (if expired)
	LspHoldtime uint32 `protobuf:"varint,4,opt,name=lsp_holdtime,json=lspHoldtime,proto3" json:"lsp_holdtime,omitempty"`
	// The LSP sequence number
	LspSequenceNumber uint32 `protobuf:"varint,5,opt,name=lsp_sequence_number,json=lspSequenceNumber,proto3" json:"lsp_sequence_number,omitempty"`
	// The LSP checksum
	LspChecksum uint32 `protobuf:"varint,6,opt,name=lsp_checksum,json=lspChecksum,proto3" json:"lsp_checksum,omitempty"`
	// TRUE if partition repair is supported
	LspParitionRepairSupportedFlag bool `protobuf:"varint,7,opt,name=lsp_parition_repair_supported_flag,json=lspParitionRepairSupportedFlag,proto3" json:"lsp_parition_repair_supported_flag,omitempty"`
	// TRUE if attached bit is set
	LspAttachedFlag bool `protobuf:"varint,8,opt,name=lsp_attached_flag,json=lspAttachedFlag,proto3" json:"lsp_attached_flag,omitempty"`
	// TRUE if the overload bit is set
	LspOverloadedFlag bool `protobuf:"varint,9,opt,name=lsp_overloaded_flag,json=lspOverloadedFlag,proto3" json:"lsp_overloaded_flag,omitempty"`
	// TRUE if the LSP is non-v1a, XXX for testing
	LspNonV1AFlag uint32 `protobuf:"varint,10,opt,name=lsp_non_v1_a_flag,json=lspNonV1AFlag,proto3" json:"lsp_non_v1_a_flag,omitempty"`
	// The type of the IS sourcing the LSP
	LspLevel string `protobuf:"bytes,11,opt,name=lsp_level,json=lspLevel,proto3" json:"lsp_level,omitempty"`
	// The total length of the LSP
	LspLength uint32 `protobuf:"varint,12,opt,name=lsp_length,json=lspLength,proto3" json:"lsp_length,omitempty"`
}

func (x *IsisShLspHeader) Reset() {
	*x = IsisShLspHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsisShLspHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsisShLspHeader) ProtoMessage() {}

func (x *IsisShLspHeader) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsisShLspHeader.ProtoReflect.Descriptor instead.
func (*IsisShLspHeader) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_rawDescGZIP(), []int{4}
}

func (x *IsisShLspHeader) GetLspId() string {
	if x != nil {
		return x.LspId
	}
	return ""
}

func (x *IsisShLspHeader) GetLocalLspFlag() bool {
	if x != nil {
		return x.LocalLspFlag
	}
	return false
}

func (x *IsisShLspHeader) GetLspActiveFlag() bool {
	if x != nil {
		return x.LspActiveFlag
	}
	return false
}

func (x *IsisShLspHeader) GetLspHoldtime() uint32 {
	if x != nil {
		return x.LspHoldtime
	}
	return 0
}

func (x *IsisShLspHeader) GetLspSequenceNumber() uint32 {
	if x != nil {
		return x.LspSequenceNumber
	}
	return 0
}

func (x *IsisShLspHeader) GetLspChecksum() uint32 {
	if x != nil {
		return x.LspChecksum
	}
	return 0
}

func (x *IsisShLspHeader) GetLspParitionRepairSupportedFlag() bool {
	if x != nil {
		return x.LspParitionRepairSupportedFlag
	}
	return false
}

func (x *IsisShLspHeader) GetLspAttachedFlag() bool {
	if x != nil {
		return x.LspAttachedFlag
	}
	return false
}

func (x *IsisShLspHeader) GetLspOverloadedFlag() bool {
	if x != nil {
		return x.LspOverloadedFlag
	}
	return false
}

func (x *IsisShLspHeader) GetLspNonV1AFlag() uint32 {
	if x != nil {
		return x.LspNonV1AFlag
	}
	return 0
}

func (x *IsisShLspHeader) GetLspLevel() string {
	if x != nil {
		return x.LspLevel
	}
	return ""
}

func (x *IsisShLspHeader) GetLspLength() uint32 {
	if x != nil {
		return x.LspLength
	}
	return 0
}

// LSP Database Log Entry
type IsisShLspDbLogEnt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Generic entry data
	GenericData *IsisShGenericLogEnt `protobuf:"bytes,1,opt,name=generic_data,json=genericData,proto3" json:"generic_data,omitempty"`
	// Operation applying to this entry.
	LspdbOperation string `protobuf:"bytes,2,opt,name=lspdb_operation,json=lspdbOperation,proto3" json:"lspdb_operation,omitempty"`
	// Entry being inserted or the updated version of an old entry.
	NewLspEntry *IsisShLspHeader `protobuf:"bytes,3,opt,name=new_lsp_entry,json=newLspEntry,proto3" json:"new_lsp_entry,omitempty"`
	// Entry being replaced.
	OldLspEntry *IsisShLspHeader `protobuf:"bytes,4,opt,name=old_lsp_entry,json=oldLspEntry,proto3" json:"old_lsp_entry,omitempty"`
}

func (x *IsisShLspDbLogEnt) Reset() {
	*x = IsisShLspDbLogEnt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsisShLspDbLogEnt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsisShLspDbLogEnt) ProtoMessage() {}

func (x *IsisShLspDbLogEnt) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsisShLspDbLogEnt.ProtoReflect.Descriptor instead.
func (*IsisShLspDbLogEnt) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_rawDescGZIP(), []int{5}
}

func (x *IsisShLspDbLogEnt) GetGenericData() *IsisShGenericLogEnt {
	if x != nil {
		return x.GenericData
	}
	return nil
}

func (x *IsisShLspDbLogEnt) GetLspdbOperation() string {
	if x != nil {
		return x.LspdbOperation
	}
	return ""
}

func (x *IsisShLspDbLogEnt) GetNewLspEntry() *IsisShLspHeader {
	if x != nil {
		return x.NewLspEntry
	}
	return nil
}

func (x *IsisShLspDbLogEnt) GetOldLspEntry() *IsisShLspHeader {
	if x != nil {
		return x.OldLspEntry
	}
	return nil
}

var File_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto protoreflect.FileDescriptor

var file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_rawDesc = []byte{
	0x0a, 0x6c, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f, 0x78, 0x72, 0x5f, 0x63,
	0x6c, 0x6e, 0x73, 0x5f, 0x69, 0x73, 0x69, 0x73, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x2f, 0x69, 0x73,
	0x69, 0x73, 0x2f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x2f, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x2f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x73, 0x2f, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x2f,
	0x69, 0x73, 0x69, 0x73, 0x5f, 0x73, 0x68, 0x5f, 0x6c, 0x73, 0x70, 0x5f, 0x64, 0x62, 0x5f, 0x6c,
	0x6f, 0x67, 0x5f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x4d,
	0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f, 0x78, 0x72, 0x5f, 0x63, 0x6c, 0x6e,
	0x73, 0x5f, 0x69, 0x73, 0x69, 0x73, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x2e, 0x69, 0x73, 0x69, 0x73,
	0x2e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x2e, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x73, 0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x22, 0x5a, 0x0a,
	0x1d, 0x69, 0x73, 0x69, 0x73, 0x5f, 0x73, 0x68, 0x5f, 0x6c, 0x73, 0x70, 0x5f, 0x64, 0x62, 0x5f,
	0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x5f, 0x4b, 0x45, 0x59, 0x53, 0x12, 0x23,
	0x0a, 0x0d, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x9f, 0x01, 0x0a, 0x18, 0x69, 0x73,
	0x69, 0x73, 0x5f, 0x73, 0x68, 0x5f, 0x6c, 0x73, 0x70, 0x5f, 0x64, 0x62, 0x5f, 0x6c, 0x6f, 0x67,
	0x5f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x12, 0x82, 0x01, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x5f, 0x65,
	0x6e, 0x74, 0x72, 0x79, 0x18, 0x32, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x65, 0x2e, 0x63, 0x69, 0x73,
	0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f, 0x78, 0x72, 0x5f, 0x63, 0x6c, 0x6e, 0x73, 0x5f, 0x69,
	0x73, 0x69, 0x73, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x2e, 0x69, 0x73, 0x69, 0x73, 0x2e, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x2e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x73, 0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x69, 0x73, 0x69, 0x73, 0x5f,
	0x73, 0x68, 0x5f, 0x6c, 0x73, 0x70, 0x5f, 0x64, 0x62, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x65, 0x6e,
	0x74, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x55, 0x0a, 0x16, 0x69,
	0x73, 0x69, 0x73, 0x5f, 0x73, 0x68, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12,
	0x21, 0x0a, 0x0c, 0x6e, 0x61, 0x6e, 0x6f, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6e, 0x61, 0x6e, 0x6f, 0x53, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x73, 0x22, 0x9f, 0x01, 0x0a, 0x17, 0x69, 0x73, 0x69, 0x73, 0x5f, 0x73, 0x68, 0x5f, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x65, 0x6e, 0x74, 0x12, 0x83,
	0x01, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x65, 0x2e, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f, 0x78,
	0x72, 0x5f, 0x63, 0x6c, 0x6e, 0x73, 0x5f, 0x69, 0x73, 0x69, 0x73, 0x5f, 0x6f, 0x70, 0x65, 0x72,
	0x2e, 0x69, 0x73, 0x69, 0x73, 0x2e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x2e,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x73, 0x2e,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x6c,
	0x6f, 0x67, 0x2e, 0x69, 0x73, 0x69, 0x73, 0x5f, 0x73, 0x68, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x22, 0xfd, 0x03, 0x0a, 0x12, 0x69, 0x73, 0x69, 0x73, 0x5f, 0x73, 0x68,
	0x5f, 0x6c, 0x73, 0x70, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x15, 0x0a, 0x06, 0x6c,
	0x73, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x73, 0x70,
	0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x6c, 0x73, 0x70, 0x5f,
	0x66, 0x6c, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x6c, 0x6f, 0x63, 0x61,
	0x6c, 0x4c, 0x73, 0x70, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x26, 0x0a, 0x0f, 0x6c, 0x73, 0x70, 0x5f,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0d, 0x6c, 0x73, 0x70, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x46, 0x6c, 0x61, 0x67,
	0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x73, 0x70, 0x5f, 0x68, 0x6f, 0x6c, 0x64, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6c, 0x73, 0x70, 0x48, 0x6f, 0x6c, 0x64, 0x74,
	0x69, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x6c, 0x73, 0x70, 0x5f, 0x73, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x11, 0x6c, 0x73, 0x70, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x73, 0x70, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x73, 0x75, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6c, 0x73, 0x70, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x12, 0x4a, 0x0a, 0x22, 0x6c, 0x73, 0x70, 0x5f, 0x70, 0x61,
	0x72, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x70, 0x61, 0x69, 0x72, 0x5f, 0x73, 0x75,
	0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x1e, 0x6c, 0x73, 0x70, 0x50, 0x61, 0x72, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x70, 0x61, 0x69, 0x72, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x46, 0x6c,
	0x61, 0x67, 0x12, 0x2a, 0x0a, 0x11, 0x6c, 0x73, 0x70, 0x5f, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68,
	0x65, 0x64, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x6c,
	0x73, 0x70, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x2e,
	0x0a, 0x13, 0x6c, 0x73, 0x70, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64,
	0x5f, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x6c, 0x73, 0x70,
	0x4f, 0x76, 0x65, 0x72, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x28,
	0x0a, 0x11, 0x6c, 0x73, 0x70, 0x5f, 0x6e, 0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x5f, 0x61, 0x5f, 0x66,
	0x6c, 0x61, 0x67, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x6c, 0x73, 0x70, 0x4e, 0x6f,
	0x6e, 0x56, 0x31, 0x41, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x73, 0x70, 0x5f,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x73, 0x70,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x73, 0x70, 0x5f, 0x6c, 0x65, 0x6e,
	0x67, 0x74, 0x68, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6c, 0x73, 0x70, 0x4c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x22, 0xdd, 0x03, 0x0a, 0x16, 0x69, 0x73, 0x69, 0x73, 0x5f, 0x73, 0x68,
	0x5f, 0x6c, 0x73, 0x70, 0x5f, 0x64, 0x62, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x65, 0x6e, 0x74, 0x12,
	0x89, 0x01, 0x0a, 0x0c, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x66, 0x2e, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69,
	0x6f, 0x73, 0x5f, 0x78, 0x72, 0x5f, 0x63, 0x6c, 0x6e, 0x73, 0x5f, 0x69, 0x73, 0x69, 0x73, 0x5f,
	0x6f, 0x70, 0x65, 0x72, 0x2e, 0x69, 0x73, 0x69, 0x73, 0x2e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x73, 0x2e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x73, 0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61,
	0x73, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x69, 0x73, 0x69, 0x73, 0x5f, 0x73, 0x68, 0x5f, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x65, 0x6e, 0x74, 0x52, 0x0b,
	0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x12, 0x27, 0x0a, 0x0f, 0x6c,
	0x73, 0x70, 0x64, 0x62, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6c, 0x73, 0x70, 0x64, 0x62, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x85, 0x01, 0x0a, 0x0d, 0x6e, 0x65, 0x77, 0x5f, 0x6c, 0x73, 0x70,
	0x5f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x61, 0x2e, 0x63,
	0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f, 0x78, 0x72, 0x5f, 0x63, 0x6c, 0x6e, 0x73,
	0x5f, 0x69, 0x73, 0x69, 0x73, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x2e, 0x69, 0x73, 0x69, 0x73, 0x2e,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x2e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x73, 0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x69, 0x73, 0x69,
	0x73, 0x5f, 0x73, 0x68, 0x5f, 0x6c, 0x73, 0x70, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52,
	0x0b, 0x6e, 0x65, 0x77, 0x4c, 0x73, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x85, 0x01, 0x0a,
	0x0d, 0x6f, 0x6c, 0x64, 0x5f, 0x6c, 0x73, 0x70, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x61, 0x2e, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73,
	0x5f, 0x78, 0x72, 0x5f, 0x63, 0x6c, 0x6e, 0x73, 0x5f, 0x69, 0x73, 0x69, 0x73, 0x5f, 0x6f, 0x70,
	0x65, 0x72, 0x2e, 0x69, 0x73, 0x69, 0x73, 0x2e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x73, 0x2e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x73, 0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65,
	0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x69, 0x73, 0x69, 0x73, 0x5f, 0x73, 0x68, 0x5f, 0x6c, 0x73, 0x70,
	0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x0b, 0x6f, 0x6c, 0x64, 0x4c, 0x73, 0x70, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_rawDescOnce sync.Once
	file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_rawDescData = file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_rawDesc
)

func file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_rawDescGZIP() []byte {
	file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_rawDescOnce.Do(func() {
		file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_rawDescData = protoimpl.X.CompressGZIP(file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_rawDescData)
	})
	return file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_rawDescData
}

var file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_goTypes = []interface{}{
	(*IsisShLspDbLogStruc_KEYS)(nil), // 0: cisco_ios_xr_clns_isis_oper.isis.instances.instance.levels.level.database_log.isis_sh_lsp_db_log_struc_KEYS
	(*IsisShLspDbLogStruc)(nil),      // 1: cisco_ios_xr_clns_isis_oper.isis.instances.instance.levels.level.database_log.isis_sh_lsp_db_log_struc
	(*IsisShTimestampType)(nil),      // 2: cisco_ios_xr_clns_isis_oper.isis.instances.instance.levels.level.database_log.isis_sh_timestamp_type
	(*IsisShGenericLogEnt)(nil),      // 3: cisco_ios_xr_clns_isis_oper.isis.instances.instance.levels.level.database_log.isis_sh_generic_log_ent
	(*IsisShLspHeader)(nil),          // 4: cisco_ios_xr_clns_isis_oper.isis.instances.instance.levels.level.database_log.isis_sh_lsp_header
	(*IsisShLspDbLogEnt)(nil),        // 5: cisco_ios_xr_clns_isis_oper.isis.instances.instance.levels.level.database_log.isis_sh_lsp_db_log_ent
}
var file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_depIdxs = []int32{
	5, // 0: cisco_ios_xr_clns_isis_oper.isis.instances.instance.levels.level.database_log.isis_sh_lsp_db_log_struc.log_entry:type_name -> cisco_ios_xr_clns_isis_oper.isis.instances.instance.levels.level.database_log.isis_sh_lsp_db_log_ent
	2, // 1: cisco_ios_xr_clns_isis_oper.isis.instances.instance.levels.level.database_log.isis_sh_generic_log_ent.timestamp:type_name -> cisco_ios_xr_clns_isis_oper.isis.instances.instance.levels.level.database_log.isis_sh_timestamp_type
	3, // 2: cisco_ios_xr_clns_isis_oper.isis.instances.instance.levels.level.database_log.isis_sh_lsp_db_log_ent.generic_data:type_name -> cisco_ios_xr_clns_isis_oper.isis.instances.instance.levels.level.database_log.isis_sh_generic_log_ent
	4, // 3: cisco_ios_xr_clns_isis_oper.isis.instances.instance.levels.level.database_log.isis_sh_lsp_db_log_ent.new_lsp_entry:type_name -> cisco_ios_xr_clns_isis_oper.isis.instances.instance.levels.level.database_log.isis_sh_lsp_header
	4, // 4: cisco_ios_xr_clns_isis_oper.isis.instances.instance.levels.level.database_log.isis_sh_lsp_db_log_ent.old_lsp_entry:type_name -> cisco_ios_xr_clns_isis_oper.isis.instances.instance.levels.level.database_log.isis_sh_lsp_header
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() {
	file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_init()
}
func file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_init() {
	if File_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsisShLspDbLogStruc_KEYS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsisShLspDbLogStruc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsisShTimestampType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsisShGenericLogEnt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsisShLspHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsisShLspDbLogEnt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_goTypes,
		DependencyIndexes: file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_depIdxs,
		MessageInfos:      file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_msgTypes,
	}.Build()
	File_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto = out.File
	file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_rawDesc = nil
	file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_goTypes = nil
	file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_database_log_isis_sh_lsp_db_log_struc_proto_depIdxs = nil
}
