// Copyright (c) 2015, Cisco Systems
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//
// 1. Redistributions of source code must retain the above copyright notice,
//    this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
// TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
// LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// This file is autogenerated
//
// The following edits are possible, without affecting the validity of the
// file:
//
//  * Fields may be renamed.
//  * Fields may be deleted.
//  * The unique numbered tag for a field may be changed, provided that
//    the ordering of tags for fields within a message is preserved.
//  * Message types may be renamed.
//  * Message types may be deleted (if all fields that reference them
//    have been deleted).
//
// All Cisco message and field extensions must be preserved (except when the
// field itself is being deleted).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: cisco_ios_xr_clns_isis_oper/isis/instances/instance/mesh_groups/isis_sh_mesh_groups.proto

package cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// IS-IS mesh-group data
type IsisShMeshGroups_KEYS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceName string `protobuf:"bytes,1,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
}

func (x *IsisShMeshGroups_KEYS) Reset() {
	*x = IsisShMeshGroups_KEYS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsisShMeshGroups_KEYS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsisShMeshGroups_KEYS) ProtoMessage() {}

func (x *IsisShMeshGroups_KEYS) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsisShMeshGroups_KEYS.ProtoReflect.Descriptor instead.
func (*IsisShMeshGroups_KEYS) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_rawDescGZIP(), []int{0}
}

func (x *IsisShMeshGroups_KEYS) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

type IsisShMeshGroups struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of mesh-group-configured interfaces
	MeshGroupConfiguredInterfaceList *IsisShMeshEntry `protobuf:"bytes,50,opt,name=mesh_group_configured_interface_list,json=meshGroupConfiguredInterfaceList,proto3" json:"mesh_group_configured_interface_list,omitempty"`
}

func (x *IsisShMeshGroups) Reset() {
	*x = IsisShMeshGroups{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsisShMeshGroups) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsisShMeshGroups) ProtoMessage() {}

func (x *IsisShMeshGroups) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsisShMeshGroups.ProtoReflect.Descriptor instead.
func (*IsisShMeshGroups) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_rawDescGZIP(), []int{1}
}

func (x *IsisShMeshGroups) GetMeshGroupConfiguredInterfaceList() *IsisShMeshEntry {
	if x != nil {
		return x.MeshGroupConfiguredInterfaceList
	}
	return nil
}

// Mesh-group informaiton for one interface
type IsisShMeshEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Next entry in list
	IsisShMeshEntry []*IsisShMeshEntryItem `protobuf:"bytes,1,rep,name=isis_sh_mesh_entry,json=isisShMeshEntry,proto3" json:"isis_sh_mesh_entry,omitempty"`
}

func (x *IsisShMeshEntry) Reset() {
	*x = IsisShMeshEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsisShMeshEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsisShMeshEntry) ProtoMessage() {}

func (x *IsisShMeshEntry) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsisShMeshEntry.ProtoReflect.Descriptor instead.
func (*IsisShMeshEntry) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_rawDescGZIP(), []int{2}
}

func (x *IsisShMeshEntry) GetIsisShMeshEntry() []*IsisShMeshEntryItem {
	if x != nil {
		return x.IsisShMeshEntry
	}
	return nil
}

type IsisShMeshEntryItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This interface
	MeshGroupInterface string `protobuf:"bytes,1,opt,name=mesh_group_interface,json=meshGroupInterface,proto3" json:"mesh_group_interface,omitempty"`
	// Mesh-group number
	MeshGroupNumber uint32 `protobuf:"varint,2,opt,name=mesh_group_number,json=meshGroupNumber,proto3" json:"mesh_group_number,omitempty"`
}

func (x *IsisShMeshEntryItem) Reset() {
	*x = IsisShMeshEntryItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsisShMeshEntryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsisShMeshEntryItem) ProtoMessage() {}

func (x *IsisShMeshEntryItem) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsisShMeshEntryItem.ProtoReflect.Descriptor instead.
func (*IsisShMeshEntryItem) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_rawDescGZIP(), []int{3}
}

func (x *IsisShMeshEntryItem) GetMeshGroupInterface() string {
	if x != nil {
		return x.MeshGroupInterface
	}
	return ""
}

func (x *IsisShMeshEntryItem) GetMeshGroupNumber() uint32 {
	if x != nil {
		return x.MeshGroupNumber
	}
	return 0
}

var File_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto protoreflect.FileDescriptor

var file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_rawDesc = []byte{
	0x0a, 0x59, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f, 0x78, 0x72, 0x5f, 0x63,
	0x6c, 0x6e, 0x73, 0x5f, 0x69, 0x73, 0x69, 0x73, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x2f, 0x69, 0x73,
	0x69, 0x73, 0x2f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x2f, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x2f, 0x6d, 0x65, 0x73, 0x68, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x73, 0x2f, 0x69, 0x73, 0x69, 0x73, 0x5f, 0x73, 0x68, 0x5f, 0x6d, 0x65, 0x73, 0x68, 0x5f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x3f, 0x63, 0x69, 0x73,
	0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f, 0x78, 0x72, 0x5f, 0x63, 0x6c, 0x6e, 0x73, 0x5f, 0x69,
	0x73, 0x69, 0x73, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x2e, 0x69, 0x73, 0x69, 0x73, 0x2e, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x2e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x2e, 0x6d, 0x65, 0x73, 0x68, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22, 0x3f, 0x0a, 0x18,
	0x69, 0x73, 0x69, 0x73, 0x5f, 0x73, 0x68, 0x5f, 0x6d, 0x65, 0x73, 0x68, 0x5f, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x73, 0x5f, 0x4b, 0x45, 0x59, 0x53, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xbb, 0x01,
	0x0a, 0x13, 0x69, 0x73, 0x69, 0x73, 0x5f, 0x73, 0x68, 0x5f, 0x6d, 0x65, 0x73, 0x68, 0x5f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0xa3, 0x01, 0x0a, 0x24, 0x6d, 0x65, 0x73, 0x68, 0x5f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x64, 0x5f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x32,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x53, 0x2e, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73,
	0x5f, 0x78, 0x72, 0x5f, 0x63, 0x6c, 0x6e, 0x73, 0x5f, 0x69, 0x73, 0x69, 0x73, 0x5f, 0x6f, 0x70,
	0x65, 0x72, 0x2e, 0x69, 0x73, 0x69, 0x73, 0x2e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x73, 0x2e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x5f,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x2e, 0x69, 0x73, 0x69, 0x73, 0x5f, 0x73, 0x68, 0x5f, 0x6d,
	0x65, 0x73, 0x68, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x20, 0x6d, 0x65, 0x73, 0x68, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x64, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x9c, 0x01, 0x0a, 0x12,
	0x69, 0x73, 0x69, 0x73, 0x5f, 0x73, 0x68, 0x5f, 0x6d, 0x65, 0x73, 0x68, 0x5f, 0x65, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x85, 0x01, 0x0a, 0x12, 0x69, 0x73, 0x69, 0x73, 0x5f, 0x73, 0x68, 0x5f, 0x6d,
	0x65, 0x73, 0x68, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x58, 0x2e, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f, 0x78, 0x72, 0x5f, 0x63,
	0x6c, 0x6e, 0x73, 0x5f, 0x69, 0x73, 0x69, 0x73, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x2e, 0x69, 0x73,
	0x69, 0x73, 0x2e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x2e, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x6d, 0x65, 0x73, 0x68, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x73, 0x2e, 0x69, 0x73, 0x69, 0x73, 0x5f, 0x73, 0x68, 0x5f, 0x6d, 0x65, 0x73, 0x68, 0x5f, 0x65,
	0x6e, 0x74, 0x72, 0x79, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x52, 0x0f, 0x69, 0x73, 0x69, 0x73, 0x53,
	0x68, 0x4d, 0x65, 0x73, 0x68, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x77, 0x0a, 0x17, 0x69, 0x73,
	0x69, 0x73, 0x5f, 0x73, 0x68, 0x5f, 0x6d, 0x65, 0x73, 0x68, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x79,
	0x5f, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x30, 0x0a, 0x14, 0x6d, 0x65, 0x73, 0x68, 0x5f, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x12, 0x6d, 0x65, 0x73, 0x68, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x6d, 0x65, 0x73, 0x68, 0x5f,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0f, 0x6d, 0x65, 0x73, 0x68, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_rawDescOnce sync.Once
	file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_rawDescData = file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_rawDesc
)

func file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_rawDescGZIP() []byte {
	file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_rawDescOnce.Do(func() {
		file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_rawDescData = protoimpl.X.CompressGZIP(file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_rawDescData)
	})
	return file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_rawDescData
}

var file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_goTypes = []interface{}{
	(*IsisShMeshGroups_KEYS)(nil), // 0: cisco_ios_xr_clns_isis_oper.isis.instances.instance.mesh_groups.isis_sh_mesh_groups_KEYS
	(*IsisShMeshGroups)(nil),      // 1: cisco_ios_xr_clns_isis_oper.isis.instances.instance.mesh_groups.isis_sh_mesh_groups
	(*IsisShMeshEntry)(nil),       // 2: cisco_ios_xr_clns_isis_oper.isis.instances.instance.mesh_groups.isis_sh_mesh_entry
	(*IsisShMeshEntryItem)(nil),   // 3: cisco_ios_xr_clns_isis_oper.isis.instances.instance.mesh_groups.isis_sh_mesh_entry_item
}
var file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_depIdxs = []int32{
	2, // 0: cisco_ios_xr_clns_isis_oper.isis.instances.instance.mesh_groups.isis_sh_mesh_groups.mesh_group_configured_interface_list:type_name -> cisco_ios_xr_clns_isis_oper.isis.instances.instance.mesh_groups.isis_sh_mesh_entry
	3, // 1: cisco_ios_xr_clns_isis_oper.isis.instances.instance.mesh_groups.isis_sh_mesh_entry.isis_sh_mesh_entry:type_name -> cisco_ios_xr_clns_isis_oper.isis.instances.instance.mesh_groups.isis_sh_mesh_entry_item
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() {
	file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_init()
}
func file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_init() {
	if File_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsisShMeshGroups_KEYS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsisShMeshGroups); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsisShMeshEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsisShMeshEntryItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_goTypes,
		DependencyIndexes: file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_depIdxs,
		MessageInfos:      file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_msgTypes,
	}.Build()
	File_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto = out.File
	file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_rawDesc = nil
	file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_goTypes = nil
	file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_mesh_groups_isis_sh_mesh_groups_proto_depIdxs = nil
}
