// Copyright (c) 2015, Cisco Systems
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//
// 1. Redistributions of source code must retain the above copyright notice,
//    this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
// TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
// LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// This file is autogenerated
//
// The following edits are possible, without affecting the validity of the
// file:
//
//  * Fields may be renamed.
//  * Fields may be deleted.
//  * The unique numbered tag for a field may be changed, provided that
//    the ordering of tags for fields within a message is preserved.
//  * Message types may be renamed.
//  * Message types may be deleted (if all fields that reference them
//    have been deleted).
//
// All Cisco message and field extensions must be preserved (except when the
// field itself is being deleted).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: cisco_ios_xr_clns_isis_oper/isis/instances/instance/levels/level/lsp_log/isis_sh_lsp_log_struc.proto

package cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// LSP-log
type IsisShLspLogStruc_KEYS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceName string `protobuf:"bytes,1,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	Level        string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *IsisShLspLogStruc_KEYS) Reset() {
	*x = IsisShLspLogStruc_KEYS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsisShLspLogStruc_KEYS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsisShLspLogStruc_KEYS) ProtoMessage() {}

func (x *IsisShLspLogStruc_KEYS) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsisShLspLogStruc_KEYS.ProtoReflect.Descriptor instead.
func (*IsisShLspLogStruc_KEYS) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_rawDescGZIP(), []int{0}
}

func (x *IsisShLspLogStruc_KEYS) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *IsisShLspLogStruc_KEYS) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type IsisShLspLogStruc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Log entries
	LogEntry []*IsisShLspLogEnt `protobuf:"bytes,50,rep,name=log_entry,json=logEntry,proto3" json:"log_entry,omitempty"`
}

func (x *IsisShLspLogStruc) Reset() {
	*x = IsisShLspLogStruc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsisShLspLogStruc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsisShLspLogStruc) ProtoMessage() {}

func (x *IsisShLspLogStruc) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsisShLspLogStruc.ProtoReflect.Descriptor instead.
func (*IsisShLspLogStruc) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_rawDescGZIP(), []int{1}
}

func (x *IsisShLspLogStruc) GetLogEntry() []*IsisShLspLogEnt {
	if x != nil {
		return x.LogEntry
	}
	return nil
}

// Timestamp for an event
type IsisShTimestampType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Timestamp value (seconds)
	Seconds uint32 `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	// Timestamp value (nanoseconds)
	NanoSeconds uint32 `protobuf:"varint,2,opt,name=nano_seconds,json=nanoSeconds,proto3" json:"nano_seconds,omitempty"`
}

func (x *IsisShTimestampType) Reset() {
	*x = IsisShTimestampType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsisShTimestampType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsisShTimestampType) ProtoMessage() {}

func (x *IsisShTimestampType) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsisShTimestampType.ProtoReflect.Descriptor instead.
func (*IsisShTimestampType) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_rawDescGZIP(), []int{2}
}

func (x *IsisShTimestampType) GetSeconds() uint32 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *IsisShTimestampType) GetNanoSeconds() uint32 {
	if x != nil {
		return x.NanoSeconds
	}
	return 0
}

// Generic portion of a log entry
type IsisShGenericLogEnt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Time in UTC relative to Jan 1st, 1970
	Timestamp *IsisShTimestampType `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *IsisShGenericLogEnt) Reset() {
	*x = IsisShGenericLogEnt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsisShGenericLogEnt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsisShGenericLogEnt) ProtoMessage() {}

func (x *IsisShGenericLogEnt) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsisShGenericLogEnt.ProtoReflect.Descriptor instead.
func (*IsisShGenericLogEnt) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_rawDescGZIP(), []int{3}
}

func (x *IsisShGenericLogEnt) GetTimestamp() *IsisShTimestampType {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// LSP-log entry
type IsisShLspLogEnt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Generic entry data
	GenericData *IsisShGenericLogEnt `protobuf:"bytes,1,opt,name=generic_data,json=genericData,proto3" json:"generic_data,omitempty"`
	// Triggers applying to this log entry.
	Triggers []string `protobuf:"bytes,2,rep,name=triggers,proto3" json:"triggers,omitempty"`
	// Number of triggers on this run. May not be equal to the number of trigger event types if one or more trigger events has occurred more than once.
	TriggerCount uint32 `protobuf:"varint,3,opt,name=trigger_count,json=triggerCount,proto3" json:"trigger_count,omitempty"`
	// Number of delayed triggers
	DelayedTriggerCount uint32 `protobuf:"varint,4,opt,name=delayed_trigger_count,json=delayedTriggerCount,proto3" json:"delayed_trigger_count,omitempty"`
	// Appropriate interface, if any
	LogInterface string `protobuf:"bytes,5,opt,name=log_interface,json=logInterface,proto3" json:"log_interface,omitempty"`
	// Pseudo-node number
	PseudoNodeNumber uint32 `protobuf:"varint,6,opt,name=pseudo_node_number,json=pseudoNodeNumber,proto3" json:"pseudo_node_number,omitempty"`
}

func (x *IsisShLspLogEnt) Reset() {
	*x = IsisShLspLogEnt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsisShLspLogEnt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsisShLspLogEnt) ProtoMessage() {}

func (x *IsisShLspLogEnt) ProtoReflect() protoreflect.Message {
	mi := &file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsisShLspLogEnt.ProtoReflect.Descriptor instead.
func (*IsisShLspLogEnt) Descriptor() ([]byte, []int) {
	return file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_rawDescGZIP(), []int{4}
}

func (x *IsisShLspLogEnt) GetGenericData() *IsisShGenericLogEnt {
	if x != nil {
		return x.GenericData
	}
	return nil
}

func (x *IsisShLspLogEnt) GetTriggers() []string {
	if x != nil {
		return x.Triggers
	}
	return nil
}

func (x *IsisShLspLogEnt) GetTriggerCount() uint32 {
	if x != nil {
		return x.TriggerCount
	}
	return 0
}

func (x *IsisShLspLogEnt) GetDelayedTriggerCount() uint32 {
	if x != nil {
		return x.DelayedTriggerCount
	}
	return 0
}

func (x *IsisShLspLogEnt) GetLogInterface() string {
	if x != nil {
		return x.LogInterface
	}
	return ""
}

func (x *IsisShLspLogEnt) GetPseudoNodeNumber() uint32 {
	if x != nil {
		return x.PseudoNodeNumber
	}
	return 0
}

var File_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto protoreflect.FileDescriptor

var file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_rawDesc = []byte{
	0x0a, 0x64, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f, 0x78, 0x72, 0x5f, 0x63,
	0x6c, 0x6e, 0x73, 0x5f, 0x69, 0x73, 0x69, 0x73, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x2f, 0x69, 0x73,
	0x69, 0x73, 0x2f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x2f, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x2f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x73, 0x2f, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x2f, 0x6c, 0x73, 0x70, 0x5f, 0x6c, 0x6f, 0x67, 0x2f, 0x69, 0x73, 0x69, 0x73, 0x5f,
	0x73, 0x68, 0x5f, 0x6c, 0x73, 0x70, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x48, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f,
	0x73, 0x5f, 0x78, 0x72, 0x5f, 0x63, 0x6c, 0x6e, 0x73, 0x5f, 0x69, 0x73, 0x69, 0x73, 0x5f, 0x6f,
	0x70, 0x65, 0x72, 0x2e, 0x69, 0x73, 0x69, 0x73, 0x2e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x73, 0x2e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x73, 0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2e, 0x6c, 0x73, 0x70, 0x5f, 0x6c, 0x6f, 0x67,
	0x22, 0x57, 0x0a, 0x1a, 0x69, 0x73, 0x69, 0x73, 0x5f, 0x73, 0x68, 0x5f, 0x6c, 0x73, 0x70, 0x5f,
	0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x5f, 0x4b, 0x45, 0x59, 0x53, 0x12, 0x23,
	0x0a, 0x0d, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x93, 0x01, 0x0a, 0x15, 0x69, 0x73,
	0x69, 0x73, 0x5f, 0x73, 0x68, 0x5f, 0x6c, 0x73, 0x70, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x12, 0x7a, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x79,
	0x18, 0x32, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x5d, 0x2e, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69,
	0x6f, 0x73, 0x5f, 0x78, 0x72, 0x5f, 0x63, 0x6c, 0x6e, 0x73, 0x5f, 0x69, 0x73, 0x69, 0x73, 0x5f,
	0x6f, 0x70, 0x65, 0x72, 0x2e, 0x69, 0x73, 0x69, 0x73, 0x2e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x73, 0x2e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x73, 0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2e, 0x6c, 0x73, 0x70, 0x5f, 0x6c, 0x6f,
	0x67, 0x2e, 0x69, 0x73, 0x69, 0x73, 0x5f, 0x73, 0x68, 0x5f, 0x6c, 0x73, 0x70, 0x5f, 0x6c, 0x6f,
	0x67, 0x5f, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x22,
	0x55, 0x0a, 0x16, 0x69, 0x73, 0x69, 0x73, 0x5f, 0x73, 0x68, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x61, 0x6e, 0x6f, 0x5f, 0x73, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6e, 0x61, 0x6e, 0x6f, 0x53,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22, 0x99, 0x01, 0x0a, 0x17, 0x69, 0x73, 0x69, 0x73, 0x5f,
	0x73, 0x68, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x65,
	0x6e, 0x74, 0x12, 0x7e, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x60, 0x2e, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f,
	0x73, 0x5f, 0x78, 0x72, 0x5f, 0x63, 0x6c, 0x6e, 0x73, 0x5f, 0x69, 0x73, 0x69, 0x73, 0x5f, 0x6f,
	0x70, 0x65, 0x72, 0x2e, 0x69, 0x73, 0x69, 0x73, 0x2e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x73, 0x2e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x73, 0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2e, 0x6c, 0x73, 0x70, 0x5f, 0x6c, 0x6f, 0x67,
	0x2e, 0x69, 0x73, 0x69, 0x73, 0x5f, 0x73, 0x68, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x22, 0xe4, 0x02, 0x0a, 0x13, 0x69, 0x73, 0x69, 0x73, 0x5f, 0x73, 0x68, 0x5f, 0x6c,
	0x73, 0x70, 0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x65, 0x6e, 0x74, 0x12, 0x84, 0x01, 0x0a, 0x0c, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x61, 0x2e, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x5f, 0x69, 0x6f, 0x73, 0x5f, 0x78, 0x72,
	0x5f, 0x63, 0x6c, 0x6e, 0x73, 0x5f, 0x69, 0x73, 0x69, 0x73, 0x5f, 0x6f, 0x70, 0x65, 0x72, 0x2e,
	0x69, 0x73, 0x69, 0x73, 0x2e, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x2e, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x73, 0x2e, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x2e, 0x6c, 0x73, 0x70, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x69, 0x73, 0x69,
	0x73, 0x5f, 0x73, 0x68, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x5f, 0x6c, 0x6f, 0x67,
	0x5f, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x08, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x73, 0x12, 0x23, 0x0a,
	0x0d, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x32, 0x0a, 0x15, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x5f, 0x74, 0x72,
	0x69, 0x67, 0x67, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x13, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65,
	0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c,
	0x6f, 0x67, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x70,
	0x73, 0x65, 0x75, 0x64, 0x6f, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10, 0x70, 0x73, 0x65, 0x75, 0x64, 0x6f, 0x4e,
	0x6f, 0x64, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_rawDescOnce sync.Once
	file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_rawDescData = file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_rawDesc
)

func file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_rawDescGZIP() []byte {
	file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_rawDescOnce.Do(func() {
		file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_rawDescData = protoimpl.X.CompressGZIP(file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_rawDescData)
	})
	return file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_rawDescData
}

var file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_goTypes = []interface{}{
	(*IsisShLspLogStruc_KEYS)(nil), // 0: cisco_ios_xr_clns_isis_oper.isis.instances.instance.levels.level.lsp_log.isis_sh_lsp_log_struc_KEYS
	(*IsisShLspLogStruc)(nil),      // 1: cisco_ios_xr_clns_isis_oper.isis.instances.instance.levels.level.lsp_log.isis_sh_lsp_log_struc
	(*IsisShTimestampType)(nil),    // 2: cisco_ios_xr_clns_isis_oper.isis.instances.instance.levels.level.lsp_log.isis_sh_timestamp_type
	(*IsisShGenericLogEnt)(nil),    // 3: cisco_ios_xr_clns_isis_oper.isis.instances.instance.levels.level.lsp_log.isis_sh_generic_log_ent
	(*IsisShLspLogEnt)(nil),        // 4: cisco_ios_xr_clns_isis_oper.isis.instances.instance.levels.level.lsp_log.isis_sh_lsp_log_ent
}
var file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_depIdxs = []int32{
	4, // 0: cisco_ios_xr_clns_isis_oper.isis.instances.instance.levels.level.lsp_log.isis_sh_lsp_log_struc.log_entry:type_name -> cisco_ios_xr_clns_isis_oper.isis.instances.instance.levels.level.lsp_log.isis_sh_lsp_log_ent
	2, // 1: cisco_ios_xr_clns_isis_oper.isis.instances.instance.levels.level.lsp_log.isis_sh_generic_log_ent.timestamp:type_name -> cisco_ios_xr_clns_isis_oper.isis.instances.instance.levels.level.lsp_log.isis_sh_timestamp_type
	3, // 2: cisco_ios_xr_clns_isis_oper.isis.instances.instance.levels.level.lsp_log.isis_sh_lsp_log_ent.generic_data:type_name -> cisco_ios_xr_clns_isis_oper.isis.instances.instance.levels.level.lsp_log.isis_sh_generic_log_ent
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() {
	file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_init()
}
func file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_init() {
	if File_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsisShLspLogStruc_KEYS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsisShLspLogStruc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsisShTimestampType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsisShGenericLogEnt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsisShLspLogEnt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_goTypes,
		DependencyIndexes: file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_depIdxs,
		MessageInfos:      file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_msgTypes,
	}.Build()
	File_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto = out.File
	file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_rawDesc = nil
	file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_goTypes = nil
	file_cisco_ios_xr_clns_isis_oper_isis_instances_instance_levels_level_lsp_log_isis_sh_lsp_log_struc_proto_depIdxs = nil
}
